### ISSUE TITLE
missing INSTALL.txt

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#106]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.15
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-02-04 15:46:21 +0000, Professor Unbearable wrote:

> A simple INSTALL.txt would be nice, like that which already exists in the SDL2 directory.
> 
> One potential issue that I would need help getting around in this file would be to find the target link libraries.
> 
> 
> This is the error I get
> 
> 
> ~/SDL2_ttf-2.0.15 $ mkdir build; cd build
> ~/SDL2_ttf-2.0.15/build $ cmake ..
> -- Configuring done
> CMake Error at CMakeLists.txt:24 (add_library):
>   Target "SDL2_ttf" links to target "SDL2::SDL2" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?
> 
> 
> CMake Error at CMakeLists.txt:24 (add_library):
>   Target "SDL2_ttf" links to target "Freetype::Freetype" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> 
> 
> -- Generating done
> -- Build files have been written to: /home/profbear/SDL2_ttf-2.0.15/build

**Comment by slouken** [comment]
@madebr, is this fixed with your CMake changes?

**Comment by madebr** [comment]
The `Freetype::Freetype` target will be created: when using system libraries it will rely on [`FindFreetype`](https://cmake.org/cmake/help/latest/module/FindFreetype.html) for creating one.
When vendoring, it will create one itself.

No `INSTALL.TXT` is created though :)

**Comment by slouken** [comment]
Okay, great.
