### ISSUE TITLE
sdl2_ttf make fails on macos bigsur m1

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#121]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [build output (sdl2_ttf_make.txt, text/plain, 2021-01-09 11:04:29 +0000, 10328 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4647)

**Reported in version:** 2.0.15
**Reported for operating system, platform:** Mac OS X (All), ARM

# Comments on the original bug report:

On 2021-01-09 11:04:29 +0000,  wrote:

> Created attachment 4647
> build output
> 
> sdl2_ttf make fails from macos bigsur on m1 arch:
> 
> "
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [libSDL2_ttf.la] Error 1
> "
> 
> i was able to build sdl2, sdl2_image, sdl2_mixer, and sdl2_ttf fails.
> please see attached build output.

On 2021-01-09 19:01:22 +0000, Cameron Gutman wrote:

> It's because the included FreeType.framework binary doesn't include arm64 code. The same situation is also true for the the Windows builds of libfreetype-6.dll (only x86 and x64, no ARM64).
> 
> As a workaround, I just grabbed the latest FreeType 2.10.4 source, built for Windows x86+x64+ARM64 and macOS x86_64+ARM64, replaced the bundled binaries in the SDL_ttf source, and then built SDL_ttf. IIRC, it required a few tweaks to the build files to pick up the newer library version, but it wasn't too bad.
> 
> It would be nice to get new SDL_ttf builds for ARM64 on Windows and macOS, or at least update the prebuilt binaries in the SDL_ttf source tree to have ARM64 builds.

**Comment by slouken** [comment]
FreeType is included in the 2.0.18 release.
