### ISSUE TITLE
Request: include harfbuzz in next SDL_ttf release

### ISSUE THREAD

**Issue by matham** [libsdl-org/SDL_ttf#123]
This is a request for the next release to contain sdl_ttf built with harfbuzz support.

This would mean also distributing the harfbuzz binaries on windows/OSX and possibly their headers (headers are needed so you can use e.g. `hb_script_from_string` harfbuzz function that generate the script value from strings to be passed to `TTF_SetScript`).

Is this something you'd consider doing?

On Windows, with MSVC it seemed fairly simple: compile harfbuzz with :
```
meson setup build --wrap-mode=default --buildtype=release -Dglib=enabled -Dfreetype=enabled -Dgdi=enabled -Ddirectwrite=enabled
meson compile -C build
```
then build sdl_ttf in powershell in a visual studio env with the relevant compiler variables set (vcvarsall etc.) with something like:
```
$env:UseEnv="true"
$env:INCLUDE="$env:INCLUDE;sdl2\SDL2;harfbuzz-2.8.0\src"
$env:LIB="$env:LIB;sdl2_bin;sdl2_libs;harfbuzz-2.8.0\build\src"
$env:CL="/DTTF_USE_HARFBUZZ#1"

cd .\SDL_ttf-main\VisualC\
devenv .\SDL_ttf.sln /Upgrade
(Get-Content .\SDL_ttf.vcxproj).replace(";%(AdditionalDependencies)",";harfbuzz.lib;%(AdditionalDependencies)") | Set-Content .\SDL_ttf.vcxproj
devenv /UseEnv .\SDL_ttf.sln  /Build "Release|x64"
```

On OSX I'm expecting it could be more difficult.

**Comment by slouken** [comment]
Harfbuzz is included in the 2.0.18 release.
