### ISSUE TITLE
configury need much revising after the freetype/harfbuzz commit 834ec54127

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_ttf#132]
Had pushed commit 9a7ef3fb640a1 as initial work. Build tested
with gcc-4.9.4 on i686-linux, with gcc-7.3.1 and clang-5.0.2 on
x86_64-linux.  clang-3.4.2 seems to fail in harfbuzz c++ code,
nothing to do about it.

May need polishing more: please have a look and test, and also
compare with harfbuzz configury.  One thing in harfbuzz is that
it checks and uses -Bsymbolic-functions linker flag: I __think__
that we don't need it.

We may also need to add required HAVE_xxx freetype flags to
harfbuzz CPPFLAGS, will look at them later.

I think the basic thing to do would be something like:
```diff
diff --git a/external/harfbuzz-2.8.0/config.h b/external/harfbuzz-2.8.0/config.h
index 89b13a5..cc8b428 100644
--- a/external/harfbuzz-2.8.0/config.h
+++ b/external/harfbuzz-2.8.0/config.h
@@ -37,9 +37,9 @@
 /* Define to 1 if you have the `FT_Done_MM_Var' function. */
-/* #define HAVE_FT_DONE_MM_VAR 1 */
+#define HAVE_FT_DONE_MM_VAR 1
 
 /* Define to 1 if you have the `FT_Get_Var_Blend_Coordinates' function. */
-/* #define HAVE_FT_GET_VAR_BLEND_COORDINATES 1 */
+#define HAVE_FT_GET_VAR_BLEND_COORDINATES 1
 
 /* Define to 1 if you have the `FT_Set_Var_Blend_Coordinates' function. */
-/* #define HAVE_FT_SET_VAR_BLEND_COORDINATES 1 */
+#define HAVE_FT_SET_VAR_BLEND_COORDINATES 1
 
 
```
However: We have HAVE_CONFIG_H in our CFLAGS, i.e. harfbuzz
has a config.h, but it's tailored for Android:  I think we should at least
remove a lot of things from it and:
- add necessary checks to SDL_ttf's top-level configure,
- add Android-specific-and-guaranteed stuff to harfbuzz Android.mk
Otherwise, build may fail e.g. with mingw (haven't tested that.)

So, still more work needed.

**Comment by 1bsyl** [comment]
Now Android/Harfbuzz has its own config.h:  (config_sdl_android.h) 
also create a pull request for HB ( https://github.com/harfbuzz/harfbuzz/pull/3015 )

**Comment by 1bsyl** [comment]
Actually keep the "config.h" naming, and use specific config inside:
see https://github.com/libsdl-org/SDL_ttf/commit/c54d9f4c696e1e55567f32cb68a8efe4e4afd521

**Comment by ericoporto** [comment]
Hey, is it possible to allow building FreeType and Harfbuzz from source in all OS and not just Android when building from CMake (maybe with an OR variable)? This would make it easier to roll Persian to all platforms for people using CMake.

**Comment by sezero** [comment]
FYI: Tried building latest tree using mingw, the custom config.h under harfbuzz is causing problems.

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/SDL_ttf/commit/441c7281fbc57a82e56ccbd2e0b2b82429fefd92 to fix several things in autotools support.

Now if only I could build the windows dll with libgcc statically linked:
@slouken, can you do it that way at your end, or is it me?

Minor stuff remaining: 
- The `config_sdl_XXX.h` under harfbuzz have `HAVE_FT_DONE_MM_VAR` and
  `HAVE_FT_GET_VAR_BLEND_COORDINATES` commented out: Do we want them
  that way? Or, should we conditionally define them depending on the
  found ft2 version (IIRC, they require ft2 >= 2.9.)

**Comment by sezero** [comment]
Is the following OK to apply? If it is, we can close this I guess.

```diff
diff --git a/external/harfbuzz-2.8.0/config_sdl_unix.h b/external/harfbuzz-2.8.0/config_sdl_unix.h
index 9d363ee..9cedf0c 100644
--- a/external/harfbuzz-2.8.0/config_sdl_unix.h
+++ b/external/harfbuzz-2.8.0/config_sdl_unix.h
@@ -35,13 +35,17 @@
 #define HAVE_FREETYPE 1
 
 /* Define to 1 if you have the `FT_Done_MM_Var' function. */
-/* #define HAVE_FT_DONE_MM_VAR 1 */
+#if ((FREETYPE_MAJOR*10000 + FREETYPE_MINOR*100 + FREETYPE_PATCH) >= 20900)
+#define HAVE_FT_DONE_MM_VAR 1
+#endif
 
 /* Define to 1 if you have the `FT_Get_Var_Blend_Coordinates' function. */
-/* #define HAVE_FT_GET_VAR_BLEND_COORDINATES 1 */
+#if ((FREETYPE_MAJOR*10000 + FREETYPE_MINOR*100 + FREETYPE_PATCH) >= 20701)
+#define HAVE_FT_GET_VAR_BLEND_COORDINATES 1
+#endif
 
 /* Define to 1 if you have the `FT_Set_Var_Blend_Coordinates' function. */
-/* #define HAVE_FT_SET_VAR_BLEND_COORDINATES 1 */
+#define HAVE_FT_SET_VAR_BLEND_COORDINATES 1
 
 /* Have GDI library */
 /* #undef HAVE_GDI */
diff --git a/external/harfbuzz-2.8.0/config_sdl_win32.h b/external/harfbuzz-2.8.0/config_sdl_win32.h
index eb61793..3036885 100644
--- a/external/harfbuzz-2.8.0/config_sdl_win32.h
+++ b/external/harfbuzz-2.8.0/config_sdl_win32.h
@@ -35,13 +35,17 @@
 #define HAVE_FREETYPE 1
 
 /* Define to 1 if you have the `FT_Done_MM_Var' function. */
-/* #define HAVE_FT_DONE_MM_VAR 1 */
+#if ((FREETYPE_MAJOR*10000 + FREETYPE_MINOR*100 + FREETYPE_PATCH) >= 20900)
+#define HAVE_FT_DONE_MM_VAR 1
+#endif
 
 /* Define to 1 if you have the `FT_Get_Var_Blend_Coordinates' function. */
-/* #define HAVE_FT_GET_VAR_BLEND_COORDINATES 1 */
+#if ((FREETYPE_MAJOR*10000 + FREETYPE_MINOR*100 + FREETYPE_PATCH) >= 20701)
+#define HAVE_FT_GET_VAR_BLEND_COORDINATES 1
+#endif
 
 /* Define to 1 if you have the `FT_Set_Var_Blend_Coordinates' function. */
-/* #define HAVE_FT_SET_VAR_BLEND_COORDINATES 1 */
+#define HAVE_FT_SET_VAR_BLEND_COORDINATES 1
 
 /* Have GDI library */
 /* #undef HAVE_GDI */
```

**Comment by sezero** [comment]
Well I went ahead and applied the above patch. Closing this.

If there are any further issues, let's discuss in a new ticket.
