### ISSUE TITLE
FT_PIXEL_MODE_GRAY16 undeclared

### ISSUE THREAD

**Issue by NePutin94** [libsdl-org/SDL_ttf#136]
I am building sdl_tff with the latest version of freetype and encountered such an error while building. 
![Снимок экрана 2021-07-02 150227](https://user-images.githubusercontent.com/25349002/124271787-8e81d880-db46-11eb-950d-7818ef83de3b.png)
 This constant was [cut](https://github.com/ArtifexSoftware/thirdparty-freetype2/blob/d3dc2da9b27af5b90575d62989389cc65fe7977c/ChangeLog#L359) from freetype, can I replace it with FT_PIXEL_MODE_GRAY4 or does this entail some problems?

**Comment by 1bsyl** [comment]
Thanks for the feedback, you can force TTF_USE_SDF to 0 to compile, line ~46

Since freetype changed this mode, I'll need to update SDL_ttf.

**Comment by NePutin94** [comment]
Okay, thanks

**Comment by 1bsyl** [comment]
@NePutin94 please give a try with latest version

**Comment by NePutin94** [comment]
thank you, now there are no build errors

**Comment by 1bsyl** [comment]
ok, thanks
