### ISSUE TITLE
configure: error: conditional "OS_WIN32" was never defined.

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL_ttf#137]
When running: 
```
configure --disable-harfbuzz
```
There is an error
```
configure: error: conditional "OS_WIN32" was never defined.
Usually this means the macro was only invoked conditionally.
```

**Comment by 1bsyl** [comment]
@sezero I believe you know how to fix this!
I commented the OS2 definition line just to get it run.

**Comment by sezero** [comment]
Should be fixed by https://github.com/libsdl-org/SDL_ttf/commit/a01c7e96b09a4bd8a5421d0d1cd39c461f2ed9b5

**Comment by 1bsyl** [comment]
yes, fixed for me, thanks !
