### ISSUE TITLE
Integer overflow in TTF_OpenFont

### ISSUE THREAD

**Issue by katp32** [libsdl-org/SDL_ttf#140]
Attempting to open a font with point size 256 or above causes the value to loop back around to zero. If this is a restriction of the library, it should probably be documented somewhere; both the documentation and the header files merely state that the type is `int`, which is generally assumed to be 32 bit, not 8 bit.

**Comment by chelmich** [comment]
I traced `ptsize` argument for `TTF_OpenFont` down and it looks like it's only used as an argument to `FT_Set_Char_Size` which actually takes a `signed long`. However, if the font isn't scalable (bitmap fonts, etc) then `ptsize` is used to select a sort of "sub-font" via `FT_Select_Size`. The relevant function is [here](https://github.com/libsdl-org/SDL_ttf/blob/70b4b80d01e076cf536ac52e22d319ed25bf5e23/SDL_ttf.c#L1705).

Could you please check if the font you're trying to open is scalable?

**Comment by katp32** [comment]
I was using DejaVu Sans Mono which, according to `fc-query`, is indeed scalable.

**Comment by chelmich** [comment]
Shoot, thanks for checking that. I'll try to reproduce it when I get a chance then.

**Comment by katp32** [comment]
Oh, it was actually `DejaVuSans-Bold.ttf`, not Mono, sorry about that.

**Comment by chelmich** [comment]
No worries. Unfortunately I tried that font and still didn't see the bug.

I have version `2.0.15` of the SDL_ttf and `2.10.4` of FreeType which I know SDL_ttf links against. Beyond that I'm kinda stumped. Do you have a small program that definitely produces the bug on your machine? If the wrapping point size shows up in `TTF_FontHeight()` then you wouldn't necessarily need to even initialize SDL2 proper.

**Comment by katp32** [comment]
Hrm, I'm now having trouble reproducing this issue, and I don't have my original code handy... it may be safe to assume then that this was a false flag. Sorry!

**Comment by chelmich** [comment]
No problem! Glad it got resolved. :)
