### ISSUE TITLE
Better Support for projects that uses add_subdirectory 

### ISSUE THREAD

**Issue by Haiderahandali** [libsdl-org/SDL_ttf#143]
the current **cmake** file assumes the user is going to install it, however I usually prefer to build standalone projects, which is why I add most external libs as sub directories via **add_subdirectory**

the current **cmake** file, requires the consumer of lib to manually copy **SDL_ttf.h** to his/her **src** directory

however, that can be easily solved by just adding this line to SDL_ttf cmake file
`target_include_directories(SDL2_ttf PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>)`

then any consumer of the lib can simply add via `add_subdirectory` and immediately include the header and link it.

**Comment by 1bsyl** [comment]
@Haiderahandali 
There is already line 
`target_include_directories(SDL2_ttf PUBLIC $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/SDL2>)`
added https://github.com/libsdl-org/SDL_ttf/commit/f34e0a8e08efdb5e074731866cf8663f8c2c0baf by @markand 

but SDL_image and SDL_mixer uses:  
`target_include_directories(SDL2_image PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})`

https://github.com/libsdl-org/SDL_ttf/commit/f34e0a8e08efdb5e074731866cf8663f8c2c0baf
https://github.com/libsdl-org/SDL_mixer/blob/master/CMakeLists.txt#L65

Maybe we should use the same nomenclature ? please submit a PR

**Comment by Haiderahandali** [comment]
@1bsyl 
Thanks for your quick reply,
I mentioned that
the support should be for add_subdirectory

> target_include_directories(SDL2_ttf PUBLIC $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/SDL2>)
if you notice the line I am using and the line you put are different
in 
**INSTALL_INTERFACE**
vs
**BUILD_INTERFACE**
I could have submitted a PR, but honestly it is a single line of code to be added, so I thought opening an issue is simpler.
(btw, SDL mixer & SDL image approach is also fine)

**Comment by 1bsyl** [comment]
@Haiderahandali 
sorry, I misread and not fully understanding the syntax & implication. I'm using all aspects that cmake provides.
Please mimic what SDL mixer/image are doing (if it's correct), and still submit a PR, so that you can also test the changes.
thanks

**Comment by cjwijtmans** [comment]
On-topic but similar issue. I am adding all dependencies through `cmake`s `FetchContent`.

```
[cmake] -- Adding external SDL2-image release-2.0.5
[cmake] -- Adding external SDL2-ttf release-2.0.15
[cmake] CMake Error at C:/usr/src/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package):
[cmake]   By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
[cmake]   asked CMake to find a package configuration file provided by "SDL2", but
[cmake]   CMake did not find one.
[cmake] 
[cmake]   Could not find a package configuration file provided by "SDL2" with any of
[cmake]   the following names:
[cmake] 
[cmake]     SDL2Config.cmake
[cmake]     sdl2-config.cmake
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

I see SDL2-ttf is using `FindPackage` but not sure how that works when dependencies are installed in `./build/_deps`. However sdl2-image doesnt have CMakeLists.txt in any tag at all.

```cmake
function(add_external project uri tag)
    if(CMAKE_VERBOSE_MAKEFILE)
        message(STATUS "Adding external ${project} ${tag}")
    endif()

    FetchContent_Declare(   ${project}
        GIT_REPOSITORY      ${uri}
        GIT_TAG             ${tag}
    )

    FetchContent_GetProperties(${project})
    set(populated ${project}_POPULATED)
    if(NOT ${poplated})
        if(CMAKE_VERBOSE_MAKEFILE)
            message(STATUS "Fetching ${uri} ${tag}")
        endif()

        FetchContent_Populate(${project})
    endif()
    FetchContent_MakeAvailable(${project})
endfunction()

add_external(SDL2-main https://github.com/libsdl-org/SDL.git release-2.0.16)
add_external(SDL2-image https://github.com/libsdl-org/SDL_image.git release-2.0.5)
add_external(SDL2-ttf https://github.com/libsdl-org/SDL_ttf.git release-2.0.15)
```

**Comment by madebr** [comment]
#213 will fix the following type of cmake script:
```cmake
cmake_minimum_required(VERSION 3.0)
project(sss C)

add_subdirectory(SDL)
add_subdirectory(SDL_image)
add_subdirectory(SDL_ttf)
```

The cmake script should also be compatible with [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html),
but you will need to add a build dependency of `SDL_image` and `SDL_ttf` on `SDL`.
