### ISSUE TITLE
Weird TTF_Init/Quit/WasInit behaviour

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL_ttf#146]
Unlike SDL\_mixer or SDL\_image, SDL\_ttf's init and quit functions behave sort of strangely. Specifically, if you call `TTF_Init` multiple times, it increments the value of `TTF_initialized` (and thus `TTF_WasInit`, which just returns that value) each time (note that `status` is always set to 0 before the following lines are run):

https://github.com/libsdl-org/SDL_ttf/blob/813740a16eaffbb1d2d8240649cb02b454c4e535/SDL_ttf.c#L1524-L1532

In other words, if you call `TTF_Init` three times in a row, `TTF_WasInit` will return 3. This wouldn't be too big a headache except for the fact that `TTF_Quit` uses a similar logic, decrementing `TTF_initialized` every time it's called but only actually de-initializing FreeType if `TTF_initialized` is 1 when the the function is called:

https://github.com/libsdl-org/SDL_ttf/blob/813740a16eaffbb1d2d8240649cb02b454c4e535/SDL_ttf.c#L3686-L3693

Thus, someone can call `TTF_Init` twice in a row and then call `TTF_Quit` once without actually quitting the library as expected. Worse, if `TTF_Quit` is somehow called *before* `TTF_Init`, `TTF_initialized` will become negative and will never quit no matter how may times it's called.

For most C programs this is a non-issue since you can easily guarantee that `TTF_Init` and `TTF_Quit` are only called once, and in that order, but for SDL2 bindings in interpreted languages (e.g. Python) there's no telling what users will do with wrapper classes or multiple imports.

An easy fix would be replacing the above chunk of `TTF_Init` with

```C
 if (!TTF_initialized) { 
     FT_Error error = FT_Init_FreeType(&library); 
     if (error) { 
         TTF_SetFTError("Couldn't init FreeType engine", error); 
         status = -1; 
     } 
     TTF_initialized = 1;
 } 
```

and replacing `TTF_Quit` with:

```C
 void TTF_Quit(void) 
 { 
     if (TTF_initialized) { 
         FT_Done_FreeType(library); 
         TTF_initialized = 0;
     } 
 } 

```

Thanks in advance for looking at this!

**Comment by 1bsyl** [comment]
@slouken do we need this TTF_initialized counter or should we simplify it ?

**Comment by slouken** [comment]
Yes, each call to init should have a matching quit call. This allows different parts of an application to work (e.g. a plugin uses SDL_ttf and the main game uses SDL_ttf independently). That's the way SDL works, and if SDL_image and SDL_mixer don't work that way, that's a bug.

We should probably protect against someone calling the quit function when it hasn't been initialized, but again, that's a bug in the application.

**Comment by 1bsyl** [comment]
ok thanks ! this makes sense and SDL_ttf is ok. Also protected if the quit function is called without been initialized (though no error logged)
let's close this
