### ISSUE TITLE
CJK line breaking rule for TTF_Render_*_Wrapped

### ISSUE THREAD

**Issue by pfhore-github** [libsdl-org/SDL_ttf#147]
CJK has a complex line breaking rule.
https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages.

Also, Chinese and Japanese (and Korean?) don't use white space between words. Instead, word wrapping can usually occur before and after any Han character, So current function cannot handle these language.

**Comment by 1bsyl** [comment]
Hi @pfhore-github 
I am not saying SDL_ttf like breaking rule is perfect, but I've tried and it wraps before/after any Han character. 
Did you try with latest head version ?

**Comment by pfhore-github** [comment]
Sorry, I test now and it works.
