### ISSUE TITLE
TTF_GlyphMetrics - returned "advance" value appears to be wrong

### ISSUE THREAD

**Issue by edbird** [libsdl-org/SDL_ttf#148]
The "advance" value returned by the function TTF_GlyphMetrics appears to be wrong.

The font I am loading is: `/usr/share/fonts/truetype/liberation2/LiberationMono-Regular.ttf`

The OS is Debian 11.

The widest character in this font set is the "_" character, which supposedly has a width of "9" pixels. It has an "advance" value of "7" pixels. (Which is universal to all characters in the font, I believe.)

Weirdly, if I take a screenshot of a printed "_" character, and open this with GIMP and zoom in to count the pixels, the width is either 8 or 7 depending if you count the "hinted" pixel. (The rendering type is "blended" so the rightmost pixel of the underscore character is only partially colored, it is partially transparent.)

Thinking about it, the "advance" value might be correct, but the "width" calculated from the "minx" and "maxx" values might be incorrect? I'm not sure about this, it is a bit confusing.

The below screenshot isn't great but should illustrate the point. The solid part of the line is 7 pixels long. There is one "hinted" pixel at the right end.

![image](https://user-images.githubusercontent.com/2939755/135723693-ce198edf-6a1d-4c7d-bb5a-98df805d5217.png)

Actually, if you zoom in further, you can see there is also a hinted font pixel on the left. The color is very close to that of the background color.

![image](https://user-images.githubusercontent.com/2939755/135723751-dd0562b2-9a8e-4a81-a7ff-0b30c3e4c7dc.png)

So the query is, why is the maxx - minx value producing "9" when the advance value is only "7"? Does this have something to do with using the "blended" rendering mode?

**Comment by 1bsyl** [comment]
Can you try with latest SDL_ttf head version ?
You can have  maxx - minx value producing "9" and advance value  "7". This isn't incoherent.
(Usually you always have blank around the glyph.)
see there for the conventions:
https://www.freetype.org/freetype2/docs/glyphs/glyphs-3.html
I don't think one should use this API, but just the text render functions.

**Comment by 1bsyl** [comment]
From https://freetype.org/freetype2/docs/glyphs/glyphs-3.html
`For example, the advance width of ‘VA’ isn't the sum of the advances of ‘V’ and ‘A’ taken separately.`
