### ISSUE TITLE
webpage: list changes in the most recent release

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#15]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2009-11-16 03:03:07 +0000,  wrote:

> The webpage at [http://www.libsdl.org/projects/SDL_ttf/] does not list the changes in the most recent release. The webpage should use headings
> like <h2 id="changes"> and <h3 id="2.0.10"> so that it is possible to link to
> [http://www.libsdl.org/projects/SDL_ttf/#changes] and
> [http://www.libsdl.org/projects/SDL_ttf/# 2.0.10].
> 
> And of course the page should be syntactically correct:
> http://validator.w3.org/

On 2012-01-02 22:09:06 +0000, Sam Lantinga wrote:

> Good idea, thanks!

**Comment by slouken** [comment]
This is implemented.
