### ISSUE TITLE
Access violation when free surface allocated by TTF_RenderText_Solid()

### ISSUE THREAD

**Issue by JamesC01** [libsdl-org/SDL_ttf#151]
I'm created a temporary surface, to convert to a texture, but when I call SDL_FreeSurface on the surface, it causes an access violation.

Here's a small code snippet:
if (m_debug_mode) {
  SDL_Surface* text_surf = TTF_RenderText_Solid(m_font, "Debug Mode", { 255, 255, 255, 255 });
  SDL_Texture* text_texture = SDL_CreateTextureFromSurface(m_renderer, text_surf);
  
  SDL_Rect dest{ 16, 16, text_surf->w, text_surf->h };
  
  SDL_FreeSurface(text_surf); // this line causes an access violation. If it's uncommented, it draws the font, but there's a leak.
  
  SDL_RenderCopy(m_renderer, text_texture, nullptr, &dest);
  
  SDL_DestroyTexture(text_texture);
		
}

I get "Access violation reading location 0xFFFFFFFFFFFFFFFF"

I'm really not sure what's happening. It seems like this person also had the same problem: [Why freeing temporary SDL_Surface causes memory reading violation](https://discourse.libsdl.org/t/why-freeing-temporary-sdl-surface-causes-memory-reading-violation/24925)

Platform: Windows 10, Visual studio
Library versions: latest release

**Comment by 1bsyl** [comment]
@JamesC01 I believe this was an issue with refcount in SDL2 and was fixed. (wasn't related to SDL_ttf)
Can you try latest SDL2 head version ? 
you can also use latest SDL2_ttf , and it's not fixed make me a testcase.

if it's easier for you, just make me a testcase that I can compile, and I'll give a try.
