### ISSUE TITLE
Behavior of "Wrapped" with small lengths

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_ttf#157]
I posted this under the SDL_ttf pre release announcement on [Discourse](https://discourse.libsdl.org/t/sdl2-ttf-2-0-18-prerelease/34240), but I also wanted to raise it here. Especially since this behavior will need to be supported as is after a release, for backwards compatibility.

I’ve been playing around with the wrapped text functions, and I’m concerned about how they handle small wrap values.

At wrap length 0, the text renders as a single line, and newline characters are still rendered as unknown characters. I expected this to behave like the normal text rendering functions but newline aware.

With a positive but very small wrap length, the text doesn’t fully show up. Or parts of letters might show up. I expected this to allocate at least enough space to put at least one character of the input string on each line.

Pinging the author of the functions @1bsyl. Thank you for all the work keeping SDL_ttf golden!

**Comment by 1bsyl** [comment]
@Starbuck5 
wrapLength 0 seems a good idea. 
Please give a try to this PR : https://github.com/libsdl-org/SDL_ttf/pull/158

> With a positive but very small wrap length, the text doesn’t fully show up. Or parts of letters might show up. I expected this to allocate at least enough space to put at least one character of the input string on each line.

We don't create a surface with more than wrapLength, so I am not sure

**Comment by Starbuck5** [comment]
Thanks for such a quick reply and PR!

I've gotten some infrastructure set up to actually build SDL_ttf locally, so I'll be able to test that tomorrow.

I figure I should provide some examples of what I'm talking about with the small wrap length weirdness.

This is using the string "hello world, how bout that?", and the font freesansbold.ttf:
At wrap length 11 (just the first char):
![11](https://user-images.githubusercontent.com/46412508/148035325-e0eba926-7412-4de1-8144-ddf7d8884b00.png)
At wrap length 12 (stuff is missing off the end):
![12](https://user-images.githubusercontent.com/46412508/148035366-4ac1ae95-7b66-4c72-82a2-56c02aad638f.png)
At wrap length 15 (a good result):
![15](https://user-images.githubusercontent.com/46412508/148035430-4f99fe0d-3cbc-4120-974e-8760830c4ca7.png)

> We don't create a surface with more than wrapLength, so I am not sure

I think it would be okay to, if needed.

**Comment by slouken** [comment]
No, the wrap length is a hard limit. You should ensure that your UI areas are large enough for at least one character if you want one character to be visible.

**Comment by slouken** [comment]
I've merged #158, thanks!

**Comment by Starbuck5** [comment]
> No, the wrap length is a hard limit. You should ensure that your UI areas are large enough for at least one character if you want one character to be visible.

Even so, the render should continue with cut off characters. Right now it seems to ditch right after one character is clipped on the side. See my examples above.

This means the string "hello world" could render very differently than "hello orld" - because "w" is a wider character, hello world could stop all rendering after encountering the "w," whereas "hello orld" would continue rendering and finish every character.

**Comment by robertpfeiffer** [comment]
I second @Starbuck5's point. Although this is an error that needs to be handled by the caller (as consistent behaviour would still result in a glitched UI), this _is_ inconsistent and surprising behaviour. Is there a way to detect if the wrapping space is too small? Is there a function PyGame could call to raise the appropriate exception when the space is too small/games implemented in C could call to detect this?

**Comment by 1bsyl** [comment]
@Starbuck5 
can you try to add here: https://github.com/libsdl-org/SDL_ttf/blob/main/SDL_ttf.c#L3386
```
             if (max_count == 0) {
                 max_count = 1;
             }   
```

**Comment by Starbuck5** [comment]
@1bsyl 

Yes, that seems to result in much more consistent behavior!

Now size 12 is:
![12](https://user-images.githubusercontent.com/46412508/148505115-425d49c4-48c8-4035-83fd-debb786c7856.png)

The two "W"s both get clipped, but the text continues. Which seems to be the way to go while keeping the rendered width the same as the wrap length.

**Comment by 1bsyl** [comment]
Thanks for the feedback, this is commited
