### ISSUE TITLE
FreeType and ZLib functions no longer exported

### ISSUE THREAD

**Issue by rtrussell** [libsdl-org/SDL_ttf#159]
FreeType and Zlib appear to be embedded in `SDL2_ttf-2.0.18.dll` rather than being supplied as separate DLLs as previously.  Unfortunately this means that functions in FreeType and Zlib which were previously exported, and could be called by the main application (for example my app calls `FT_Library_Version()` and `gzopen()` etc.), are no longer available.

Can I request that if FreeType and ZLib are going to be embedded, their public functions are added to the DLL's export table.

**Comment by slouken** [comment]
This is intentional so that it doesn't conflict with the application's own usage of FreeType.

**Comment by rtrussell** [comment]
> This is intentional so that it doesn't conflict with the application's own usage of FreeType.

Except that my application simply stops working, because it cannot find the FreeType and ZLib functions.  It works correctly in Linux and in MacOS, but no longer in Windows with SDL_ttf-2.0.18.  It's a regression.

**Comment by slouken** [comment]
If your application uses FreeType and Zlib, then it should link with them. Feel free to continue using the previous version of SDL_ttf or publish an update to your application.

**Comment by rtrussell** [comment]
> If your application uses FreeType and Zlib, then it should link with them.

Distributing the FreeType and Zlib DLLs **alongside** SDL2_ttf (which already contains them) would bloat my package by an entirely unnecessary 600 Kb or so.  Anyway given that the very reason for calling `FT_Library_Version()` is to find out the version of FreeType being **used by** SDL2_ttf (see below) it would be pointless!

I can't see that any 'conflict' necessarily arises if you export the public FreeType and Zlib functions from the SDL2_ttf DLL.  If the app doesn't want to use them it can still use late-binding to get the entry points for separate FreeType and Zlib DLLs at run-time if it chooses.

![aboutbox](https://user-images.githubusercontent.com/42455052/148134807-5605fbf2-2501-44f7-b451-aee7859f726e.png)

**Comment by sezero** [comment]
> [...] functions in FreeType and Zlib which were previously exported, and could be called by

I just looked at the previous SDL2_ttf 2.0.14 dlls and they only and only exported their own TTF_??? symbols.

**Comment by rtrussell** [comment]
> I just looked at the previous SDL2_ttf 2.0.14 dlls and they only exported their own TTF_??? symbols.

True, but they didn't embed FreeType and Zlib in the same DLL: it was necessary to use them alongside **libfreetype-6.dll** and **zlib1.dll**.  Running an app which uses SDL2_ttf caused all **three** DLLs to be loaded, and their exported functions were available to the app.  Now that's not the case (in Windows).

Mine can't be the only app which wants to know the version of FreeType being used by SDL2_ttf, if only to report that information to the user.  On all other platforms, and on Windows prior to 2.0.18, that is simply a case of calling `FT_Init_FreeType()`, `FT_Library_Version()` and `FT_Done_FreeType()`.  Now it doesn't work.

**Comment by sezero** [comment]
You can still build SDL2_ttf yourself using Visual Studio, which, as I remember, is still _old style_.

**Comment by rtrussell** [comment]
> You can still build SDL2_ttf yourself using Visual Studio, which, as I remember, is still _old style_.

I am concerned about the regression in respect of the pre-compiled DLLs available from libsdl.org, which previously supported (e.g.) finding the version of FreeType used by SDL2_ttf but in 2.0.18 does not.

**Comment by sezero** [comment]
> I am concerned about the regression

No offense, but what you did was your abuse and the new dll 
has no regressions.

**Comment by rtrussell** [comment]
> but what you did was your abuse

I do not understand how it is "abuse" to want to know the version of FreeType in use.   The function `TTF_Linked_Version()` is provided to discover the version of SDL2_ttf, so it is presumably considered to be of value to the calling program.  But the version of FreeType has **more** effect on the way text is rendered, so surely the calling program has at least as much legitimate interest in knowing that?

**Comment by sezero** [comment]
The way I see it, all we can do here is adding a new api procedure like `TTF_FreeTypeVersion` or something, wrapping around `FT_Library_Version`, and I don't know whether maintainers would be OK with that.

**Comment by 1bsyl** [comment]
If TTF_FreeTypeVersion is the only function to add, why not ..

**Comment by slouken** [comment]
FreeType and harfbuzz are now embedded on every platform.

**Comment by rtrussell** [comment]
> FreeType and harfbuzz are now embedded on every platform.

Even when FreeType is a standard component of the OS (such as on Android and iOS)?  That seems like a wasteful duplication.

I can see it causing problems for me on Linux, when my app is relying on the libraries available from that distro's repository.  If a user updates SDL2_ttf, and as a result FreeType and Zlib are no longer loaded as dependencies, older versions of my app will simply stop working.  So much for compatibility!

It is my opinion that you should make every effort to ensure that an update to (e.g.) SDL2_ttf won't break an existing app, even if it does something that can be argued to be bad practice.  I had no reason to think that relying on FreeType and Zlib being loaded as dependencies was risky, since it worked on every platform.

**Comment by slouken** [comment]
Again, you should never rely on implicit library dependencies. If you need to link with a library like FreeType, you should explicitly link with it.

**Comment by rtrussell** [comment]
> If you need to link with a library like FreeType, you should explicitly link with it.

But, as I've said, since what I am trying to discover is the version of FreeType **used by** SDL2_ttf, explicitly linking with it doesn't help because I may end up getting the version number of a **different** FreeType library, not the embedded one!

As far as I know SDL2_ttf (currently) provides **no way** of discovering the version of FreeType it is using, so I still consider that in those circumstances calling `FT_Library_Version()` from my app is entirely legitimate. 

Are you going to provide a `TTF_FreeTypeVersion()` or similar API in the final released SDL2_ttf-2.0.18.dll ?

**Comment by slouken** [comment]
Yes, I think that's a good idea. Thanks for the suggestion.

**Comment by sezero** [comment]
Is the following good, then?
```diff
diff --git a/SDL_ttf.c b/SDL_ttf.c
index 5359737..c9d1b54 100644
--- a/SDL_ttf.c
+++ b/SDL_ttf.c
@@ -279,7 +279,7 @@ struct _TTF_Font {
 #define TTF_STYLE_NO_GLYPH_CHANGE   (TTF_STYLE_UNDERLINE | TTF_STYLE_STRIKETHROUGH)
 
 /* The FreeType font engine/library */
-static FT_Library library;
+static FT_Library library = NULL;
 static int TTF_initialized = 0;
 static SDL_bool TTF_byteswapped = SDL_FALSE;
 
@@ -1544,6 +1544,12 @@ int TTF_Init(void)
     return status;
 }
 
+void TTF_GetFTVersion(int *major, int *minor, int *patch)
+{
+    SDL_assert(sizeof(int) == sizeof(FT_Int)); /* just in case. */
+    FT_Library_Version(library, major, minor, patch);
+}
+
 static unsigned long RWread(
     FT_Stream stream,
     unsigned long offset,
@@ -3742,6 +3748,7 @@ void TTF_Quit(void)
     if (TTF_initialized) {
         if (--TTF_initialized == 0) {
             FT_Done_FreeType(library);
+            library = NULL;
         }
     }
 }
diff --git a/SDL_ttf.h b/SDL_ttf.h
index 7bba393..1fbaef6 100644
--- a/SDL_ttf.h
+++ b/SDL_ttf.h
@@ -84,6 +84,11 @@ extern "C" {
  */
 extern DECLSPEC const SDL_version * SDLCALL TTF_Linked_Version(void);
 
+/* This function stores the version of the FreeType2 library in use.
+   TTF_Init() should be called before using.
+ */
+extern DECLSPEC void SDLCALL TTF_GetFTVersion(int *major, int *minor, int *patch);
+
 /* ZERO WIDTH NO-BREAKSPACE (Unicode byte order mark) */
 #define UNICODE_BOM_NATIVE  0xFEFF
 #define UNICODE_BOM_SWAPPED 0xFFFE
```

**Comment by slouken** [comment]
Let's call it TTF_GetFreeTypeVersion(), but otherwise it looks good.
Can we add TTF_GetHarfBuzzVersion() as well?

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/SDL_ttf/commit/e4fad3787eabb765d1a04f6fee78b85bebe8a6be
Push any revisions necessary, if any.

**Comment by slouken** [comment]
Pushed https://github.com/libsdl-org/SDL_ttf/commit/87e45339635e8fb9420b4b2812a5550361e6c1c2, thanks!
