### ISSUE TITLE
Add text align and line spacing to SDL_ttf?

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_ttf#160]
With the new Wrapped functions adding automatic line wrapping, it would be cool to get support for line spacing and text alignment as well.

I've got it working locally (hardcoded), and the code in the `wrapped` functions makes it really easy to integrate these features.

This could handle aligns if wired together properly (comments are what I added) (around line 3515 in the current source)
```c
        /* right align */
        //xstart += wrapLength - line_width;

        /* center align */
        //xstart += wrapLength / 2 - line_width / 2;

        /* Render one text line to textbuf at (xstart, ystart) */
        if (Render_Line(render_mode, font->render_subpixel, font, textbuf, xstart, ystart, fg.a) < 0) {
            goto failure;
        }
```

For text spacing, it seems to work fine just multiplying lineskip (on ~line=3432) by some scalar. For line spacing, I've been imagining it as a scale, not as an absolute number of pixels. So lineskip=1 is default, lineskip=1.5 puts more space in between each line, etc.

This might be burdensome to add to the `Wrapped` functions as they are now because users would have to specify these arguments, which would be inconvenient to those who just want to throw in some simple multi line text. So instead, perhaps it could be added as a series of `WrappedEx` functions.

I'd be happy to submit a PR for this.

@1bsyl what do you think? (sorry to keep pestering you about line wrapping features 😄)

**Comment by 1bsyl** [comment]
We could add new function like TTF_SetLineSkip()  and TTF_SetLineAlignement() for instance to set some style configuration.
I think you can submit a PR for that.

It's not possible to change the wrapped prototype !
And it doesn't seem reasonable to add a new wrapped function for this.

If we want to add a more complex wrapped function, we may want more things: like bidi, multiples ttf arguments, more styles maybe ...

**Comment by slouken** [comment]
I'm wondering if maybe we want to create a "meta" font rendering function that takes text and a parameter struct that has extended options. What do you think, @1bsyl?

**Comment by 1bsyl** [comment]
If it's only alignment and lineSkip, the usual 1 api seems fine. And it's already what we have for other settings.
I don't think we will add much more.
But we could even build meta struct interface on top of those function, so can get/set the current style

The Wrapped API are anyway limited if people want to mix various things inside color/style/font etc.
If one want something more complex or specific, it is built top of the Render functions.

**Comment by slouken** [comment]
https://github.com/libsdl-org/SDL_ttf/pull/161 is merged!
