### ISSUE TITLE
Download links for old releases?

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL_ttf#162]
Hi there,

I maintain the PySDL2 Python bindings for SDL2 and its mixer/ttf/image add-on libraries. As part of my CI testing process, I fetch the official Windows/macOS binaries for various older releases to make sure my bindings work properly with them (important since a lot of LTS Linux distros have very old SDL2/ttf/mixer/image versions).

Since the release of TTF 2.0.18 today (yay!), the libsdl.org page with all the releases (`https://www.libsdl.org/projects/SDL_ttf/release`) is now a redirect to the GitHub release page, which is fine but make it impossible to easily download/test the binaries from old releases.

Are the old binaries hosted somewhere else now? If not, could they please be uploaded to somewhere easily accessible (e.g. archive.org)?

Thanks in advance!

**Comment by slouken** [comment]
The old releases are back on libsdl.org: https://www.libsdl.org/projects/SDL_ttf/release/

Thanks!

**Comment by a-hurst** [comment]
Fantastic. Thanks so much!

**Comment by slouken** [comment]
You're welcome! :)
