### ISSUE TITLE
vcxproj absolute path

### ISSUE THREAD

**Issue by baidwwy** [libsdl-org/SDL_ttf#172]
https://github.com/libsdl-org/SDL_ttf/blob/164dd650976a75cc39ef0f5cbe89b826594ca0f9/VisualC/SDL_ttf.vcxproj#L88

**Comment by slouken** [comment]
Fixed, in https://github.com/libsdl-org/SDL_ttf/commit/05220721bac0c8325250691a6d1e38569421953d, thanks!
