### ISSUE TITLE
TTF_SetDirection and TTF_SetScript both require HarfBuzz constants/headers

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL_ttf#175]
Hi there,

With the new 2.0.18 release, TTF added functions that allow you to set the text direction and script type for the underlying HarfBuzz library. This is great, except that SetDirection requires HarfBuzz constants as an input and SetScript requires a value from the HarfBuzz `HB_TAG` macro as an input, making it difficult to use these functions without also importing the HarfBuzz headers.

Given that the SetDirection constants and `HB_TAG` macro are pretty simple, would you consider adding TTF-specific alternatives to them for these functions? e.g `TTF_DIRECTION_LTR` instead of `HB_DIRECTION_LTR`, `TTF_SCRIPT` instead of `HB_TAG`, etc. That would help make TTF fully self-contained, and also make it easier to document down the road.

Thanks in advance!

**Comment by slouken** [comment]
Yes, that seems like a good idea, thanks!

**Comment by 1bsyl** [comment]
@a-hurst @slouken 
Here's some type that could be used in place of hb types to simply compilation
@a-hurst can you try ?

**Comment by a-hurst** [comment]
@1bsyl Great! A couple questions/comments:

1. Why are the top-to-bottom and bottom-to-top direction constants commented out? Just not something TTF officially supports?
2. How would one go about testing the TTF\_SetScript function? I'm guessing you'd need an Arabic font or something and try setting the script to see if it renders any different? I don't actually have an immediate use case for either function, I just noticed the HarfBuzz constant/macro dependency while updating the PySDL2 bindings and thought it was worth mentioning.
3. To avoid the maintenance burden of all the `TTF_SCRIPT_` constants, I think it's fine as an end-user  to just have the `TTF_TAG` macro that converts the standardized ISO 15924 4-character codes to SetScript's required input format. All the possible 4-letter codes for different script styles are [already documented on unicode.org(https://unicode.org/iso15924/iso15924-codes.html), the only issue I can think of is TTF's HarfBuzz not supporting a newly-added ISO script tag and having no way to check for an error if it isn't available (though the lack of error checking is a problem with the current release as well).

**Comment by 1bsyl** [comment]
So this was added in: https://github.com/libsdl-org/SDL_ttf/commit/6dcf9e6f2341a482cc6461b885c5063b49096787

` int TTF_SetFontScriptName(TTF_Font *font, const char *script) `
