### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by svanimpe** [libsdl-org/SDL_ttf#179]
I have installed SDL and SDL_ttf through Homebrew (formulas **sdl2** and **sdl2_ttf**). The installed versions are SDL 2.0.20, SDL_ttf 2.0.18 and FreeType 2.11.1. The **freetype** formula was not built with HarfBuzz support, as you can check here:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/freetype.rb

However, when I call `TTF_Linked_Version`, `TTF_GetFreeTypeVersion`, and `TTF_GetHarfBuzzVersion`, I get the following results:

SDL_ttf 2.0.18
FreeType 2.10.4
HarfBuzz 2.8.0

Why is this?

**Comment by sezero** [comment]
You built your SDL_ttf using embedded versions of freetype and harfbuzz. If you want to build against system-wide installed versions of freetype and harfbuzz, configure using `--disable-freetype-builtin --disable-harfbuzz-builtin`.

Closing. If the solution doesn't help, then please re-open with details.

**Comment by svanimpe** [comment]
Ah, so the source of confusion is that the [sdl2_ttf formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/sdl2_ttf.rb) lists FreeType as a dependency, even though it builds with an embedded version?

**Comment by sezero** [comment]
Looks like it, yes: If you want to build using the embedded versions then you can drop the freetype and harfbuzz dependencies. Or if you want to build against system versions, then you should update your formula with the configure switches I mentioned above.

**Comment by carlocab** [comment]
For anyone following along:

Homebrew/homebrew-core#94541
Homebrew/homebrew-core#94505
