### ISSUE TITLE
Can't link statically to x64 MinGW 2.0.18 release

### ISSUE THREAD

**Issue by sharkwouter** [libsdl-org/SDL_ttf#182]
At the moment I'm trying to build a static binary using the MinGW release. I've installed MinGW on an Ubuntu container and extracted the release in the MinGW root. Then I try to build with the ``-static`` flag set and I'm using pkg-config with the ``--static`` flag to get a list of what to link to in CMake.

The container and the Dockerfile can be found here: https://github.com/sharkwouter/mingw-game-builder

SDL2_ttf gets installed here: https://github.com/sharkwouter/mingw-game-builder/blob/0ac063427107035345088bc8ed386f1aa197c8d8/Dockerfile#L49-L52

The game I'm trying to build is one I made myself called OceanPop. I'm trying this approach because I got sick of waiting 10 minutes for vcpkg to build the dependencies every time I'm building for Windows in the GitHub CI. It can be found here (mingw branch): https://github.com/sharkwouter/oceanpop/tree/mingw

I'm building here: https://github.com/sharkwouter/oceanpop/blob/088fd2b9247755a41d02c6448f0724e9150c4dc8/.github/workflows/build.yml#L42-L43

The relevant part of the CMakeLists.txt is here: https://github.com/sharkwouter/oceanpop/blob/088fd2b9247755a41d02c6448f0724e9150c4dc8/CMakeLists.txt#L197-L213

It does build, but it's failing to link with the following error:

```
[  4%] Linking CXX executable oceanpop.exe
/usr/bin/x86_64-w64-mingw32-ld: /usr/lib/gcc/x86_64-w64-mingw32/9.3-win32/../../../../x86_64-w64-mingw32/lib/libSDL2_ttf.a(libSDL2_ttf_la-hb-uniscribe.o):/Users/valve/release/SDL_ttf/SDL2_ttf-2.0.18-source/foo-x64/../external/harfbuzz-2.8.0/src/hb-uniscribe.cc:343: undefined reference to `__imp_UuidCreate'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/oceanpop.dir/build.make:430: oceanpop.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/oceanpop.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
``

**Comment by slouken** [comment]
It looks like you need to link with Rpcrt4.lib - the ming32 equivalent might be -lrpcrt4 ?
https://docs.microsoft.com/en-us/windows/win32/api/rpcdce/nf-rpcdce-uuidcreate

**Comment by sharkwouter** [comment]
Oh you're right, thank you very much! That is the solution. Does that mean pkg-config should return this too? Or is that too specific?

**Comment by slouken** [comment]
It looks like maybe it should be listed in Libs.private? Can we get the opinion of someone more familiar with that system?

**Comment by sezero** [comment]
Is the following patch OK?
```diff
diff --git a/configure.ac b/configure.ac
index e047d8f..a3b4d45 100644
--- a/configure.ac
+++ b/configure.ac
@@ -218,10 +218,11 @@ if test x$enable_harfbuzz = xyes; then
 		  *-*-mingw*) hb_os_win32=yes
 			CXXFLAGS="$CXXFLAGS -static-libgcc -static-libstdc++"
 			CFLAGS="$CFLAGS -static-libgcc"
 			# for uniscribe support:
 			TTF_LIBS="$TTF_LIBS -lusp10 -lgdi32 -lrpcrt4"
+			PC_LIBS="$PC_LIBS -lusp10 -lgdi32 -lrpcrt4"
 		  ;;
 		esac
 		case "$host" in
 		  arm-*-*)
 		    if test "x$ac_cv_alignof_struct_char__" != x1; then
@@ -260,10 +261,11 @@ if test x$enable_harfbuzz = xyes; then
 		if test x$harfbuzz = xyes; then
 			AC_DEFINE(TTF_USE_HARFBUZZ, 1, [])
 			PC_REQUIRES="harfbuzz $PC_REQUIRES"
 			TTF_CFLAGS="$TTF_CFLAGS $HB_CFLAGS"
 			TTF_LIBS="$TTF_LIBS $HB_LIBS"
+			PC_LIBS="$PC_LIBS $HB_LIBS"
 			SUMMARY="${SUMMARY}Using harfbuzz      : YES\n"
 		else
 			AC_MSG_ERROR([dnl
 *** Unable to find HarfBuzz library (https://harfbuzz.github.io)])
 		fi

diff --git a/configure b/configure
index 5b39876..93a59d3 100755
--- a/configure
+++ b/configure
@@ -18550,6 +18550,7 @@ _ACEOF
 			CFLAGS="$CFLAGS -static-libgcc"
 			# for uniscribe support:
 			TTF_LIBS="$TTF_LIBS -lusp10 -lgdi32 -lrpcrt4"
+			PC_LIBS="$PC_LIBS -lusp10 -lgdi32 -lrpcrt4"
 		  ;;
 		esac
 		case "$host" in
@@ -18677,6 +18678,7 @@ $as_echo "$harbuzz_has_freetype" >&6; }
 			PC_REQUIRES="harfbuzz $PC_REQUIRES"
 			TTF_CFLAGS="$TTF_CFLAGS $HB_CFLAGS"
 			TTF_LIBS="$TTF_LIBS $HB_LIBS"
+			PC_LIBS="$PC_LIBS $HB_LIBS"
 			SUMMARY="${SUMMARY}Using harfbuzz      : YES\n"
 		else
 			as_fn_error $? "*** Unable to find HarfBuzz library (https://harfbuzz.github.io)" "$LINENO" 5
```

**Comment by ccawley2011** [comment]
> ```diff
> @@ -260,10 +261,11 @@ if test x$enable_harfbuzz = xyes; then
>  		if test x$harfbuzz = xyes; then
>  			AC_DEFINE(TTF_USE_HARFBUZZ, 1, [])
>  			PC_REQUIRES="harfbuzz $PC_REQUIRES"
>  			TTF_CFLAGS="$TTF_CFLAGS $HB_CFLAGS"
>  			TTF_LIBS="$TTF_LIBS $HB_LIBS"
> +			PC_LIBS="$PC_LIBS $HB_LIBS"
>  			SUMMARY="${SUMMARY}Using harfbuzz      : YES\n"
>  		else
>  			AC_MSG_ERROR([dnl
>  *** Unable to find HarfBuzz library (https://harfbuzz.github.io)])
>  		fi
> 
> ```

This bit shouldn't be necessary, since harfbuzz is already added to `PC_REQUIRES`.

**Comment by sezero** [comment]
Patch applied as https://github.com/libsdl-org/SDL_ttf/commit/b8f6d5b6af4ed92bf172e5c22f9ed82a69738a4a
