### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by 1a7r0ch3** [libsdl-org/SDL_ttf#183]
Previous project page offered prebuilt binaries. Is is still possible to get them somewhere?

**Comment by flambard-took** [comment]
Also missing are `.tar.gz` source distributions (those are a bit different from github download archive option).

**Comment by Starbuck5** [comment]
They're both on here: https://www.libsdl.org/projects/SDL_ttf/release/

**Comment by sezero** [comment]
The project has a chicken-egg problem: https://github.com/libsdl-org/SDL_ttf lists http://libsdl.org/projects/SDL_ttf as the project site url, but that itself redirects to github project, therefore people don't see the release files as they should. @slouken should remove the redirection from the libsdl.org project site.

**Comment by slouken** [comment]
Prebuilt binaries are available on the release page:
https://github.com/libsdl-org/SDL_ttf/releases/tag/release-2.0.18

**Comment by sezero** [comment]
https://github.com/libsdl-org/SDL_ttf/issues/183#issuecomment-1070572621

**Comment by slouken** [comment]
I removed the website link from github, since that's the authoritative repository now.
