### ISSUE TITLE
Alignment fault in TTF_RenderText_Solid

### ISSUE THREAD

**Issue by adam4235** [libsdl-org/SDL_ttf#192]
The following issue found that there seems to be a memory alignment issue in TTF_RenderText_Solid:

https://github.com/emscripten-core/emscripten/issues/14870

I'm not sure of the details or whether this is considered a bug.  It's probably mainly a potential performance or optimization issue.

**Comment by slouken** [comment]
This should be fixed in the latest SDL_ttf code, thanks!
