### ISSUE TITLE
Why is this difficult to build...

### ISSUE THREAD

**Issue by adsCrazyDiamond** [libsdl-org/SDL_ttf#197]
Can you please just make available the SDL_ttf libraries... is there a git that just includes those libraries for building? I'm not interested in the example programs or any of this very large amount of extra stuff here. A simple git that allows one to type make and have the SDL_ttf.h and supporting libraries pop out the other end would be lovely.

Just so you know when you attempt to build this in windows with mingw this is what you're greeted with... after the 10 minute wait for configure to finish....

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh '/c/SDL_ttf-main/missing' aclocal-1.16 -I acinclude
/c/SDL_ttf-main/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [Makefile:866: aclocal.m4] Error 127

 truly annoying to have to install 4 or 5 more programs just to build these libraries.

**Comment by sezero** [comment]
Clone the git repository and cd into it, and run `./touch-autofoo.sh`: That will skip any autoreconf attempts, and it will work because the git repo has the generated files up-to-date already.

**Comment by sezero** [comment]
Closing this. If you still run into autotools issues, please re-open.
