### ISSUE TITLE
Put harfbuzz header in external/ ?

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_ttf#207]
I rebased to work on fixing a PR of mine up for being ready to merge, and suddenly the build fails, where it hadn't before.

```
SDL_ttf.c:85:10: fatal error: 'hb.h' file not found
#include <hb.h>
         ^~~~~~
1 error generated.
```

This seems like an oversight with what's included with the bundled libraries in external.

**Comment by 1bsyl** [comment]
@Starbuck5 harfbuzz / freetype where added as submodules

you need to do:
git submodule init
git submodule update

maybe that's the issue

**Comment by Starbuck5** [comment]
Thanks @1bsyl that was exactly it!

Do you think it was just because I had a pre existing clone locally, or is this a new step that everyone will need to take, because we could add it to the README then.

Never used submodules before, but it looks cool.

**Comment by 1bsyl** [comment]
This is a recent thing (also affecting SDL_image and mixer).
I'm not really familiar with it, but I have had to do this also.
I'd say it could probably be automatic seeing how much git can be customized.

Stackoverflow there is:

`git config --global submodule.recurse true`
https://stackoverflow.com/questions/4611512/is-there-a-way-to-make-git-pull-automatically-update-submodules/49427199#49427199

but not sure ..
