### ISSUE TITLE
Build SDL_ttf with vendored libraries

### ISSUE THREAD

**Issue by rmg-nik** [libsdl-org/SDL_ttf#208]
I suggest add the ability to build SDL_ttf with vendored libraries (freetype and harfbuzz) the same way as SDL_image are builded with libpng/libjpeg/etc.

For example in SDL_image

```
        if (SUPPORT_JPG_VENDORED)
            set(jpeg OFF)
            add_subdirectory(external/jpeg EXCLUDE_FROM_ALL)
            add_library(JPEG::JPEG ALIAS jpeg)
            list(APPEND INSTALL_EXTRA_TARGETS jpeg)
        else()
            find_package(JPEG REQUIRED)
            list(APPEND PC_REQUIRES libjpeg)
        endif()
```

**Comment by madebr** [comment]
I will start working on this once I have SDL_image's cmake fully working (apart from its dependency issues).
I think some issues I'm facing there are also present here.
I'm making good progress, so I'll be able to move here soon.

**Comment by slouken** [comment]
Okay, great!
