### ISSUE TITLE
Re-enable HAVE_NEON_INTRINSICS

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL_ttf#215]
It seems to me ARM_NEON is working and could be re-activated: 
https://github.com/libsdl-org/SDL_ttf/blob/main/SDL_ttf.c#L122

```diff
diff --git a/SDL_ttf.c b/SDL_ttf.c
index 8a4bb3d..68909ea 100644
--- a/SDL_ttf.c
+++ b/SDL_ttf.c
@@ -119,7 +119,7 @@ int TTF_SetScript(int script) /* hb_script_t */
 #endif
 
 /* Round glyph width to 16 bytes use NEON instructions */
-#if 0 /*defined(__ARM_NEON)*/
+#if defined(__ARM_NEON)
 #  define HAVE_NEON_INTRINSICS 1
 #endif

```

**Comment by sezero** [comment]
Does it build / work on windows versions too?

**Comment by 1bsyl** [comment]
I haven't re-tried that, I think it did (window for window arm platform). never try compiling on windows for android.
I probably can double-check (later..)

**Comment by slouken** [comment]
What testing have you done to verify it?

**Comment by 1bsyl** [comment]
I haven't done more testing recently. (I'll try the window compilation more later).
I don't know why this is back-out.
I've using these neon intrinsic routines for years now on android without special crash about it

**Comment by 1bsyl** [comment]
I have some trouble to try the ARM compilation of SDL_ttf on window.
I have no device, my Visual Studio is old (2017) and not configured for ARM.
Would be nice if someone with a setup ready could try it.

**Comment by sezero** [comment]
Is this planned for 2.20 ?

**Comment by slouken** [comment]
> Is this planned for 2.20 ?

No, nobody has a setup to test it, so it'll have to go in post-release.

**Comment by slouken** [comment]
They were disabled in b264dfe2ed931668d3496dde56f9f7425948162d because of compiler errors. I don't remember what environment I was seeing that, probably some Android NDK version. I'll try re-enabling it here and see if I still see this issue.

**Comment by 1bsyl** [comment]
btw, I have always kept the neon intrinsics activated without seeing any issue.

With new NDK, it may need the header:
`#include <arm_neon.h>`


Otherwise, still have some issue to compile harfbuzz, and I use an older version on android:
cd external/harfbuzz && git checkout  43931e3e596c04044861770b831c8f9452e2d3b0
and that patch
```
+++ b/src/hb.hh
@@ -133,6 +133,7 @@
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#pragma GCC diagnostic ignored "-Wtype-limits"
#pragma GCC diagnostic ignored "-Wc++11-compat" // only gcc raises it
+#pragma GCC diagnostic ignored "-Wcast-function-type-strict"
#endif
```
