### ISSUE TITLE
SDL_FreeSurface causes a crash when used on surface drawn to by TTF_RenderTextSolid/Blended

### ISSUE THREAD

**Issue by davidcbeaudoin** [libsdl-org/SDL_ttf#218]
I've encountered a weird issue where whenever I try to use SDL_FreeSurface on an SDL_Surface modified by TTF_RenderTextSolid or TTF_RenderTextBlended, I'm getting a crash where the message from my IDE is EXC_BAD_ACCESS. When I inspect the SDL_Surface variable following a crash using the debugger, it's pointing to a valid instance. What's unusual is I'm using SDL_FreeSurface calls elsewhere in my codebase for freeing other surfaces and not having the same issue.

Here is the code where I'm performing the calls:

`SDL_Surface *textSurface = TTF_RenderText_Solid("Arial.ttf", text.c_str(), color);
    
    if (textSurface == NULL)
    {
        std::cout << "TTF_RenderText failed: " << TTF_GetError() << std::endl;
        return;
    }
    else
    {
        SDL_Texture *textTexture = GenerateSdlTexture(textSurface);
        
        if (textTexture == NULL)
        {
            std::cout << "SDL_CreateTextureFromSurface failed: " << SDL_GetError() << std::endl;
            return;
        }
        else
        {
            int w = textSurface->w;
            int h = textSurface->h;
            
            SDL_Rect destRect;
            destRect.x = destLoc->x;
            destRect.y = destLoc->y;
            destRect.w = w;
            destRect.h = h;
            
            // Calls another function with the SDL_RenderCopy call
            RenderTexture(textTexture, NULL, &destRect, true);
        }
        
        // This causes the crash
        SDL_FreeSurface(textSurface);
}`

I don't know if it makes any difference, but I'm developing on an M1X (Apple Silicon) Mac with macOS Monterey using Xcode 13.3.

**Comment by madebr** [comment]
If you're comfortable around CMake, can you try the cmake script at https://github.com/libsdl-org/SDL_ttf/pull/213?
```
git fetch origin pull/213/head:pr213
git checkout pr213
```

**Comment by davidcbeaudoin** [comment]
I'm not familiar with using CMake. 

I don't know if this will lend any insight whatsoever as to what might be wrong with the SDL_Surface, but I attached a screenshot of the crash message and the details of the instance.

![image](https://user-images.githubusercontent.com/32605877/168845091-560f2041-61ba-4e5b-b92a-dce489d81cd3.png)
