### ISSUE TITLE
pysdl2 test fails after upgrading 2.0.18 to 2.19.1

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL_ttf#221]
[py-sdl2](https://github.com/py-sdl/py-sdl2) has this:

```
        ret = sdlttf.TTF_SetDirection(HB_DIRECTION_LTR)
        assert ret == 0
        # Try changing the script direction to see if it has any effect
        w1, h1, w2, h2 = c_int(0), c_int(0), c_int(0), c_int(0)
        sdlttf.TTF_SizeText(font, b"Hi there!", byref(w1), byref(h1))
        ret = sdlttf.TTF_SetDirection(HB_DIRECTION_TTB)
        assert ret == 0
        sdlttf.TTF_SizeText(font, b"Hi there!", byref(w2), byref(h2))
        sdlttf.TTF_SetDirection(HB_DIRECTION_LTR) # Reset direction
        assert w1.value > w2.value
```

(This is a Python binding for SDL using ctypes, but the mapping to the C API is reasonably obvious.)

This worked with 2.0.18, but doesn't work as intended since 1b2f2d7. Previously, all font rendering used the global and script, and would change as soon as the global variables changed; but now, the font object remembers the value of the global variable at the time it was created, and subsequent changes to the global variable won't affect pre-existing font objects.

I don't know whether any actual games rely on this.

**Comment by smcv** [comment]
One way to get the same semantics that the py-sdl test is checking for, while still keeping the new feature from 1b2f2d7 working, would be to treat `font->hb_direction` and `font->hb_script` as being per-font overrides for the global variables, with the default being "don't override":

* keep the global variables as-is
* initialize `font->hb_direction` and `font->hb_script` to `HB_DIRECTION_INVALID` and `HB_SCRIPT_INVALID`
* every time those struct members are used, if their value is `INVALID`, use the value of the global variable instead

**Comment by sezero** [comment]
I don't _think_ the behavior change was intentional in that commit and it should be changed back, IMO. @1bsyl?

**Comment by slouken** [comment]
> One way to get the same semantics that the py-sdl test is checking for, while still keeping the new feature from [1b2f2d7](https://github.com/libsdl-org/SDL_ttf/commit/1b2f2d7b142ac090519b03a8213977e091f724dc) working, would be to treat `font->hb_direction` and `font->hb_script` as being per-font overrides for the global variables, with the default being "don't override":
> 
> * keep the global variables as-is
> * initialize `font->hb_direction` and `font->hb_script` to `HB_DIRECTION_INVALID` and `HB_SCRIPT_INVALID`
> * every time those struct members are used, if their value is `INVALID`, use the value of the global variable instead

Yes, that's the right fix here.

**Comment by smcv** [comment]
I'll try to get a PR implementing that today.
