### ISSUE TITLE
CMake package config tries to include non-existent SDL_ttf-targets.cmake file

### ISSUE THREAD

**Issue by JornVernee** [libsdl-org/SDL_ttf#226]
The cmake package config file `SDL2_ttfConfig.cmake` tries to `include` the file `SDL_ttf-targets.cmake` ([at the bottom of that file](https://github.com/libsdl-org/SDL_ttf/blob/main/SDL2_ttfConfig.cmake.in#L18)). But, the file generated by the build is called:  `SDL2_ttf-${sdl2_ttf_install_name_infix}-targets.cmake` (https://github.com/libsdl-org/SDL_ttf/blob/main/CMakeLists.txt#L276)

As a result, the `include` fails with an error similar to the following:

```
CMake Error at <SDL_ttf install prefix>/cmake/SDL2_ttfConfig.cmake:18 (include):
  include could not find requested file:

    <SDL_ttf install prefix>/cmake/SDL2_ttf-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:276 (find_package)
 ```
 
A possible solution is to change the name of the target file inside `SDL_ttfConfig.cmake` like so:

    include("${CMAKE_CURRENT_LIST_DIR}/SDL2_ttf-@sdl2_ttf_install_name_infix@-targets.cmake")
    
The [`configure_package_config_file`](https://github.com/libsdl-org/SDL_ttf/blob/main/CMakeLists.txt#L267) call should then expand this to the right target file name.

**Comment by madebr** [comment]
Good find, I'll fix asap!
