### ISSUE TITLE
Render Directly to a streaming texture

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#23]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [protype patch (patch_bug_1399_ttf_streaming_texture.difff, text/plain, 2018-11-13 09:48:34 +0000, 6246 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3484)

**Reported in version:** unspecified
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2012-01-27 10:24:11 +0000, Rodrigo Cardoso wrote:

> That's it, the summary is self explanatory =]
> 
> Would be much easier and faster when using SDL_Textures.
> 
> thanks!

On 2012-01-28 07:27:13 +0000, Sam Lantinga wrote:

> This is something we can add in the SDL2 upgrade.

On 2018-11-13 09:48:34 +0000, Sylvain wrote:

> Created attachment 3484
> protype patch
> 
> This is a prototype for rendering text directly to streaming texture.
> patch is diff'ed with bug 4361, and test-case app will be updated in bug 4374
> 
> It renders to a SD_Texture created with SDL_TEXTUREACCESS_STREAMING and format SDL_PIXELFORMAT_ARGB8888.
> Only "Blended" is done. Not sure that it makes senses to do Solid/Shaded, as they are palletized surfaces and that would require a conversion.
> 
> Prototype/name of the function is:
> 
> int TTF_RenderUTF8_Texture(TTF_Font *font, SDL_Texture *texture, const char *text, SDL_Color fg)
> 
> But it should probably also include some dest x/y position.
> The function doesn't add much rendering complexity as it only prepares datas and calls "Render_Line()".

**Comment by slouken** [comment]
We've added more advanced capability with TTF_Text in SDL_ttf 3.0. You can now render to a surface (which can be created from a streaming texture) or render it directly using the 2D rendering API.
