### ISSUE TITLE
Wrong version number 2.20.0.0 instead of 2.0.20.0

### ISSUE THREAD

**Issue by Spatzendame** [libsdl-org/SDL_ttf#231]
please make new release

**Comment by slouken** [comment]
That is the correct version.

See https://github.com/libsdl-org/SDL/issues/5217 for discussion.

**Comment by sezero** [comment]
@slouken: The 2.20.0 tag is correct, but the release is incorrectly named `2.0.20` instead of 2.20.0: that one needs correcting.
