### ISSUE TITLE
Font rendering broken when linked to HarfBuzz > 4.3.0?

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL_ttf#232]
Just caught this problem testing out PySDL2 with the latest `SDL2_ttf` installed with homebrew, which recently updated its HarfBuzz from 4.3.0 to 4.4.1. For whatever reason, a change between these two versions breaks how TTF calculates character widths with HarfBuzz enabled such that  updating a font's size with `TTF_SetFontSize` increasing the character size while only minimally affecting character spacing, so characters get squished together. When I manually uninstalled brew's harfbuzz 4.4.1 and reinstalled 4.3.0, the problem was immediately fixed. You can see the difference immediately with the PySDL2 `ttf.py` demo:

All the below images are using `SDL_ttf` 2.20.0 installed from Homebrew on macOS 12:

Font opened at 20pt (HarfBuzz 4.3.0):
<img width="912" alt="Screen Shot 2022-07-21 at 7 20 32 PM" src="https://user-images.githubusercontent.com/18648066/180325296-11d7c4b7-43e2-41f3-a6a2-0c8e3f79ee0e.png">
Font resized to 30pt with `TTF_SetFontSize` (HarfBuzz 4.3.0):
<img width="912" alt="Screen Shot 2022-07-21 at 7 20 23 PM" src="https://user-images.githubusercontent.com/18648066/180325610-cbe78b82-8089-4329-aa00-efd068610130.png">
Font opened at 20pt (HarfBuzz 4.4.1):
<img width="912" alt="Screen Shot 2022-07-21 at 7 21 14 PM" src="https://user-images.githubusercontent.com/18648066/180325637-18c9c037-2bab-43d0-a7b6-f23e3d9ed99d.png">
Font resized to 30pt with `TTF_SetFontSize` (HarfBuzz 4.4.1):
<img width="912" alt="Screen Shot 2022-07-21 at 7 21 24 PM" src="https://user-images.githubusercontent.com/18648066/180325699-4d119fd2-011b-4ad7-872a-b22f193d6ab1.png">

I don't have enough C knowledge to really help track down the cause, but I figured I should let you know before more distros and package managers update their HarfBuzz versions!

**Comment by slouken** [comment]
Can you please report this upstream to HarfBuzz?

**Comment by a-hurst** [comment]
@slouken Just did! Hopefully it's an easy fix.

**Comment by slouken** [comment]
Thanks!

**Comment by behdad** [comment]
I'm looking into this. Can you share the sample app?

**Comment by behdad** [comment]
> I'm looking into this. Can you share the sample app?

Nevermind. I can reproduce this now.

**Comment by sezero** [comment]
Mainstream seems to have fixed this by https://github.com/harfbuzz/harfbuzz/commit/cb5ca6be29ef61d13b2d0dae7cf3fbf740ae20ec

Close this?
