### ISSUE TITLE
SDL_ttf 2.20.0 functions not exported in Windows x64 lib

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_ttf#233]
I was having trouble (unresolved external error) using a new function, `TTF_SetFontScriptName`, so I checked the exports of the DLL / lib I was using with MSVC's dumpbin tool.

The new functions in SDL_ttf 2.20.0 were shown from the DLL, but not from the lib file. Specifically the symbols 
```
TTF_GetFontWrappedAlign
TTF_RenderGlyph32_LCD
TTF_RenderGlyph_LCD
TTF_RenderText_LCD
TTF_RenderText_LCD_Wrapped
TTF_RenderUNICODE_LCD
TTF_RenderUNICODE_LCD_Wrapped
TTF_RenderUTF8_LCD
TTF_RenderUTF8_LCD_Wrapped
TTF_SetFontDirection
TTF_SetFontScriptName
TTF_SetFontWrappedAlign
```

I looked at MSVC-devel x64 SDL_ttf 2.20.0 lib.

**Comment by slouken** [comment]
Ah good catch. Fixed, thanks!
https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.0/SDL2_ttf-devel-2.20.0-VC.zip
