### ISSUE TITLE
CMake minimum version set to 3.14 but CMakeLists.txt contains features from 3.21 

### ISSUE THREAD

**Issue by kleszcz** [libsdl-org/SDL_ttf#234]
While minimum required version of cmake is set to 3.14 when building shared libs ` file(COPY_FILE)` is used for installation and it's a [3.21](https://cmake.org/cmake/help/latest/command/file.html#copy-file) feature. Either bump the minimum version to 3.21 or fallback to `file(COPY)`

Tested on Ubuntu 20.04 with cmake 3.20.  Note that while using a higher version of cmake everything works and no complaint is made by cmake during generation as instructions are part of `install(CODE)` so they are not checked against cmake version.

**Comment by madebr** [comment]
Fixed by https://github.com/libsdl-org/SDL_ttf/commit/c5478b14d639afc405f03c5bbdddbde58b4981bb

Please re-open if you think this solution is not sufficient.

**Comment by sezero** [comment]
SDL_rtf has the same issue.

**Comment by madebr** [comment]
Fixed in https://github.com/libsdl-org/SDL_rtf/commit/b5a9ad3808b19c6532ddd21edbbb07074c3625b8 (includes a bonus fix)

**Comment by sezero** [comment]
Thanks
