### ISSUE TITLE
Failing to compile with harfbuzz 4.4.1

### ISSUE THREAD

**Issue by mikelatiolais** [libsdl-org/SDL_ttf#236]
I'm trying to install SDL_ttf on OSX Monterey from the repo. I created a symlink in external pointing to my harfbuzz source, and copied the .deps directory over. 
It compiles fine until it hits this:
make: *** No rule to make target `external/harfbuzz/src/hb-ms-feature-ranges.cc', needed by `external/harfbuzz/src/libSDL2_ttf_la-hb-ms-feature-ranges.lo'.  Stop.

Has something been deprecated? I'm not seeing that file anywhere in the harfbuzz source, only a header.

**Comment by madebr** [comment]
The vendored harfbuzz/freetype libraries in `external` are pinned to a single version, and cannot be changed easily.
If you really need to use a specific freetype/harfbuzz library, you need to build those libraries outside of SDL_ttf, and use configure options to link to it.

```
...
Optional Features:
...
  --enable-harfbuzz       Enable HarfBuzz [default=yes]
  --enable-harfbuzz-builtin
                          Use included version of HarfBuzz [default=yes]
...

Some influential environment variables:
...
  PKG_CONFIG_PATH
              directories to add to pkg-config's search path
...
  HB_CFLAGS   C compiler flags for HB, overriding pkg-config
  HB_LIBS     linker flags for HB, overriding pkg-config
```

So you need to build and install harfbuzz to a directory (e.g. `/tmp/harfbuzz_install`),
and run SDL_ttf as e.g.
```sh
PKG_CONFIG_PATH=/tmp/harfbuzz_install/lib/pkgconfig /path/to/sdl_ttf/configure --enable-harfbuzz --enable-harfbuzz-builtin=no
```
(untested)


PS: We're bumping harfbuzz to the latest in https://github.com/libsdl-org/SDL_ttf/pull/306
