### ISSUE TITLE
SDL2_ttf homebrew's cmake config script does not work

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_ttf#237]
When using the `SDL2_ttf` package packaged by Homebrew, the following error occurs:
```
CMake Error in CMakeLists.txt:
  Imported target "SDL2_ttf::SDL2_ttf" includes non-existent path
    "//include/SDL2"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
```

Using `--trace`, the output contains:
```
2022-07-24T00:03:47.7969560Z /usr/local/lib/cmake/SDL2_ttf/sdl2_ttf-config.cmake(18):  get_filename_component(prefix ${CMAKE_CURRENT_LIST_DIR}../../../../../../../../.. ABSOLUTE )
2022-07-24T00:03:47.7970080Z /usr/local/lib/cmake/SDL2_ttf/sdl2_ttf-config.cmake(19):  set(exec_prefix ${prefix} )
2022-07-24T00:03:47.7970560Z /usr/local/lib/cmake/SDL2_ttf/sdl2_ttf-config.cmake(20):  set(bindir ${exec_prefix}/bin )
2022-07-24T00:03:47.7971040Z /usr/local/lib/cmake/SDL2_ttf/sdl2_ttf-config.cmake(21):  set(includedir ${prefix}/include )
2022-07-24T00:03:47.7971560Z /usr/local/lib/cmake/SDL2_ttf/sdl2_ttf-config.cmake(22):  set(libdir /usr/local/Cellar/sdl2_ttf/2.20.0/lib )
```
The relative path to the prefix is completely wrong + libdir contains an absolute build folder path.

I believe this error happens because the algorithm to calculate the root directory of a package relative to another directory is flawed.
This error renders the cmake configuration of homebrew virtually useless.

https://github.com/libsdl-org/SDL_ttf/blob/760844903a196c315e0f421cefbfb7c3748c76af/configure.ac#L363-L367

Perhaps we should consider using [`ax_compute_relative_paths`](https://www.gnu.org/software/autoconf-archive/ax_compute_relative_paths.html)? Its license allows embedding in configure scripts of whatever license.

All SDL2 libraries depend on this to get the path of SDL2 libraries and headers.
So this is kind of a breaking bug for all libraries.

Relevant links:
- [sdl2_ttf homebrew recipe](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/sdl2_ttf.rb#L37-L40)
- [default configure args](https://github.com/Homebrew/brew/blob/5080312bdd6abee6066291e3b3b7b3f15d249b64/Library/Homebrew/formula.rb#L1479)

I encountered this issue on CI. Because I don't own a Mac, I'm unable to dive deeper into this.

**Comment by sezero** [comment]
I'd say go for it.

License isn't an issue I think - we have a few other m4 macros from autoconf-archive 
under SDL, although not used currently.

**Comment by sezero** [comment]
One thing that comes to mind with `AX_COMPUTE_RELATIVE_PATHS` is how
does it work with windows paths with drive letters, e.g. `c:/some/path`,
because it expects colon separated triplets.

**Comment by madebr** [comment]
This is meant to end up in configure, which is a configure script that runs on bash.
So on Windows, the configure script will be run inside e.g. msys2 or wsl2.
In there, the Windows drive letter should normally be replaced with a unix path.

On `msys2`, `c:\some\path` becomes `/c/some/path`

**Comment by turbocat2001** [comment]
@slouken, hello! The problem is still not fixed. 
```
CMake Error in CMakeLists.txt:
  Imported target "SDL2_ttf::SDL2_ttf" includes non-existent path

    "//include/SDL2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
And this in ArchLinux.

Reopen the bug, it reproduces almost everywhere, the thing is that `sdl2_ttf-config.cmake` does not have this line config.cmake.in#L17. I fixed it and submitted a pull request: #303.  The error can be reproduced by the following reproducer: [bug_sdl2_ttf.tar.gz](https://github.com/libsdl-org/SDL_ttf/files/12451124/bug_sdl2_ttf.tar.gz). I also believe that all other sdl2_* are affected by this error. Why it was not found before is unknown. For some reason, I use self-written cmake search modules instead of the built-in ones.

**Comment by madebr** [comment]
I'll try to reproduce it in a arch docker container.

**Comment by madebr** [comment]
I can reproduce this error when configuring with `-DCMAKE_PREFIX_PATH=/`.
When passing no arguments, it succeeds building.

It looks like config files generated by CMake also do `REALPATH`, so thanks for the patch!

**Comment by slouken** [comment]
Does SDL3 need this fix as well?
