### ISSUE TITLE
Update causes breakage of Hedgewars labels

### ISSUE THREAD

**Issue by l29ah** [libsdl-org/SDL_ttf#239]
![screenshot](https://issues.hedgewars.org/attachment.cgi?id=148)
sdl2-ttf 2.0.15 works good, 2.0.18 is broken
The first bad commit could be any of:
303fee0b68a7eec0126fb47105d7a06704b97bc2
cc44108a8fff5496041c955e267ad3ab9b35ab54
31589bd7316d946d2eb122afaed68bc9b9b0fceb
9a6863a61f4918826e2135c70f5b9963f5ff7a15
414904c17f6cc0ebf02a6f7df160fe925303c498
We cannot bisect more!

After discussion in #hedgewars, the maintainer have skimmed through the commits and couldn't understand whether the issue is in sdl or hedgewars. Hedgewars bug report: https://issues.hedgewars.org/show_bug.cgi?id=838

**Comment by slouken** [comment]
Sylvain, can you take a look?

**Comment by l29ah** [comment]
fixed in http://hg.hedgewars.org/hedgewars/rev/c4561095666a
