### ISSUE TITLE
Inconsistent CMake version requirements

### ISSUE THREAD

**Issue by greye** [libsdl-org/SDL_ttf#244]
Top-level CMakeListst.txt declares minimum supported CMake version as 3.14, but uses DEPRECATION[1] target property at line 404 that was introduced in 3.17.

1. https://cmake.org/cmake/help/latest/prop_tgt/DEPRECATION.html

**Comment by madebr** [comment]
The `DEPRECATION` property is only set when `CMAKE_VERSION` is >= 3.17, see

https://github.com/libsdl-org/SDL_ttf/blob/ff952bc8ddc072ebea64cda6c8f27d49097d8eae/CMakeLists.txt#L399-L403

This is the 2nd issue reporting this, see #234.
How are you using SDL_ttf?

**Comment by greye** [comment]
Fixed in the upstream then, I'm fine with it. The issue is present in `2.20.1` source distribution tarball[^tar].

[^tar]: https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.1/SDL2_ttf-2.20.1.tar.gz

**Comment by madebr** [comment]
Thanks, I pushed the fix to e49b603 so it will be part of the next patch release.

**Comment by greye** [comment]
That's great, thanks!
