### ISSUE TITLE
CMake Error: file does not recognize sub-command COPY_FILE

### ISSUE THREAD

**Issue by jboadas** [libsdl-org/SDL_ttf#245]
Build with cmake with these commands
```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release --parallel

#CMake >= 3.15
sudo cmake --install . --config Release
```
My cmake version is: 3.18.4

Everything goes well until performing the cmake install with this command:
```
sudo cmake --install . --config Release
```
Got this error:
```
CMake Error at cmake_install.cmake:130 (file):
  file does not recognize sub-command COPY_FILE
```

On the cmake [CMakeLists.txt](https://github.com/libsdl-org/SDL_ttf/blob/main/CMakeLists.txt), says `cmake_minimum_required(VERSION 3.16)`

Any clues on how to build with cmake?

**Comment by madebr** [comment]
c5478b14d639afc405f03c5bbdddbde58b4981bb fixed this in main.
I pushed b016a3e for the next 2.20.x patch release.
