### ISSUE TITLE
Question about UTF-8 encoded strings and grapheme clusters

### ISSUE THREAD

**Issue by klei1984** [libsdl-org/SDL_ttf#249]
I have a use case to draw UTF-8 encoded strings on screen with a type writer effect. A type writer effect gives users the impression that text is being typed onto the screen.

As far as I can tell the SDL_ttf API does not support fetching code points or human perceived characters, grapheme clusters, from UTF-8 strings. If I got the implementation right the library is able to convert UTF-8 encoded grapheme clusters to UTF-32 code units using both FreeType and Harfbuzz internally, but does not expose these capabilities to the users.

Would it be possible to expose such an API?

**Comment by slouken** [comment]
Yes, that seems like a good idea. Feel free to submit a PR that implements this.

**Comment by slouken** [comment]
This is out of scope for SDL_ttf. If you generate grapheme clusters, SDL_ttf should be able to render them, but it doesn't have the information necessary to parse them individually. SDL 3.0 does have SDL_StepUTF8(), but it only reads individual code points, not grapheme clusters. If you find a good library for this, or want to add it to SDL, please let me know!
