### ISSUE TITLE
Raspberry Pi OS Lite compilation error

### ISSUE THREAD

**Issue by fxlevy** [libsdl-org/SDL_ttf#258]
Hello, I'm facing an issue when compiling from release 2.20.0 on my Raspberry Pi 4B with latest Raspberry Pi OS Lite.
Any compilations with the same directives on release 2.0.18 and before work fine.

I use the following previous command before starting the make
./configure --without-x

At the end of the configuration phase I have those new messages:
SDL2_ttf Configure Summary:
Using included FreeType : YES
Using HarfBuzz          : YES
Using included HarfBuzz : YES

When launching the make command, I have now the following message:

make: *** No rule to make target 'external/freetype/src/autofit/autofit.c', needed by 'external/freetype/src/autofit/libSDL2_ttf_la-autofit.lo'.  Stop.

And then the error:

SDL_ttf.c:28:10: fatal error: ft2build.h: No such file or directory
   28 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.

Of course the file is present in /usr/include/freetype2/

Adding -I/usr/include/freetype2/ in CFLAGS of Makefile generates another include error but this time on hb.h include.

**Comment by madebr** [comment]
Is `SDL2_ttf-2.20.0/external/freetype/src/autofit/autofit.c` present?

By default, the autotools script uses vendored copies of freetype and harfbuzz.
To use your system libraries, configure with:
```
../configure --disable-harfbuzz-builtin --disable-freetype-builtin --without-x
```

**Comment by fxlevy** [comment]
Thanks for the quick feedback.
The SDL2_ttf-2.20.0/external/freetype/src/autofit/ folder is empty.

For information I downloaded from the repo the ziped source files at
https://github.com/libsdl-org/SDL_ttf/archive/refs/tags/release-2.20.1.zip
and didn't change any content.

What do you mean by 'By default, the autotools script uses vendored copies of freetype and harfbuzz.'?
Just before the build I installed the libfreetype6-dev library as the standard procedure recomends it.

Is there a new procedure to install SDL_ttf from the 2.20.x release?
Is there any documentation on building instructions?
How should we identify those new features?

Anyway, applying the new configuration options generates now new messages at the end of the configuration phase.
SDL2_ttf Configure Summary:
Using included FreeType : NO
Using HarfBuzz          : YES
Using included HarfBuzz : NO
Using harfbuzz      : YES

But now, during make phase,  a new error is raised:

/usr/local/include/SDL2/SDL_stdinc.h:382:42: error: static assertion failed: "SDL_TTF_PATCHLEVEL == SDL_BUILD_MICRO_VERSION"
  382 | #define SDL_COMPILE_TIME_ASSERT(name, x) _Static_assert(x, #x)
      |                                          ^~~~~~~~~~~~~~
SDL_ttf.c:66:1: note: in expansion of macro ‘SDL_COMPILE_TIME_ASSERT’
   66 | SDL_COMPILE_TIME_ASSERT(SDL_BUILD_MICRO_VERSION,
      | ^~~~~~~~~~~~~~~~~~~~~~~

just before, to double check, i rebuilt SDL latest release 2.26.2 without any issues and without any specific configuration option. Meaning that I removed my previous option CFLAGS='-mcpu=cortex-a72'.

**Comment by 1bsyl** [comment]
The SDL2_ttf-2.20.0/external/freetype/src/autofit/ folder is empty.
you should use git to grab the third party sub-modules

**Comment by 1bsyl** [comment]
run
https://github.com/libsdl-org/SDL_ttf/blob/main/external/download.sh

**Comment by fxlevy** [comment]
Thanks for your quick feedback. :)

I supposed your proposal by executing the download.sh script is to download the vendors copies of freetype and harfbuzz in their respective external folders.
I did it. Now both external vendors folders are not empty.

I have the same whatever is the configuration options used
../configure --without-x
../configure --disable-harfbuzz-builtin --disable-freetype-builtin --without-x

In both cases i have the same messages when executing the make command:

In file included from /usr/local/include/SDL2/SDL_main.h:25,
                 from /usr/local/include/SDL2/SDL.h:32,
                 from ../SDL_ttf.c:22:
/usr/local/include/SDL2/SDL_stdinc.h:382:42: error: static assertion failed: "SDL_TTF_PATCHLEVEL == SDL_BUILD_MICRO_VERSION"
  382 | #define SDL_COMPILE_TIME_ASSERT(name, x) _Static_assert(x, #x)
      |                                          ^~~~~~~~~~~~~~
../SDL_ttf.c:66:1: note: in expansion of macro ‘SDL_COMPILE_TIME_ASSERT’
   66 | SDL_COMPILE_TIME_ASSERT(SDL_BUILD_MICRO_VERSION,
      | ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:1539: libSDL2_ttf_la-SDL_ttf.lo] Error 1

**Comment by 1bsyl** [comment]
not sure what happens

comment out those insert to see if it compiles ...

maybe you should have the --prefix setting also somewhere. same as for sdl2 build

**Comment by fxlevy** [comment]
For the SDL2 build I downloaded the latest source release-2.26.2.zip from the repo.
Then I made a fresh install of the latest Raspberry Pi OS Lite on the Raspi 4B 8Go 
Because there is no Window system installed I installed the following libraries:
"libfreetype6-dev libdrm-dev libgbm-dev libudev-dev libdbus-1-dev libasound2-dev liblzma-dev libjpeg-dev libtiff-dev libwebp-dev libgles2-mesa-dev"

Then i Configure the SDL build with the following options
--disable-video-opengl --disable-video-opengles1 --disable-video-x11 --disable-pulseaudio --disable-esd --disable-video-wayland --disable-video-rpi --disable-video-vulkan --enable-video-kmsdrm --enable-video-opengles2 --enable-alsa --enable-arm-neon --enable-arm-simd

Finally i built with the following make option dedicated to the Raspi4b.
CFLAGS='-mcpu=cortex-a72

Everything was fine for the SDL build... no error.
I made a SDL test program which worked just fine.
And the kmscube test program also works just fine.

Then for the SDL_ttf, 
I downloaded Vendors freetype and harfbuzz using the download.sh from git.
I configured using only the --without-x option and then make.

This is where the issue happens during build.
 
I don't understand what you mean by 'maybe you should have the --prefix setting also somewhere. same as for sdl2 build'. I didn't do anything special for the SDL build. I dont see what you mean when talking about --prefix.

**Comment by madebr** [comment]
You downloaded the SDL2_ttf source tarball that GitHub automatically generates: it does not contain git submodules.
We also provide a tarball that includes sources for all dependencies: [`SDL2_ttf-2.20.1.tar.gz`](https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.1/SDL2_ttf-2.20.1.tar.gz).

On my x64 dev machine, when I run `../configure --enable-harfbuzz-builtin=no  --enable-freetype-builtin=no`, followed by `make`, `SDL_ttf.c` is compiled with the command:
```
libtool: compile:  gcc -DPACKAGE_NAME=\"SDL2_ttf\" -DPACKAGE_TARNAME=\"SDL2_ttf\" -DPACKAGE_VERSION=\"2.20.1\" "-DPACKAGE_STRING=\"SDL2_ttf 2.20.1\"" -DPACKAGE_BUGREPORT=\"https://github.com/libsdl-org/SDL_ttf/issues\" -DPACKAGE_URL=\"\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=20 -DSDL_BUILD_MICRO_VERSION=1 -DPACKAGE=\"SDL2_ttf\" -DVERSION=\"2.20.1\" -DTTF_USE_HARFBUZZ=1 -DTTF_USE_HARFBUZZ=1 -I. -I.. -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -I/usr/include/SDL2 -D_REENTRANT -Wall -fvisibility=hidden -DHAVE_OPENGL -MT libSDL2_ttf_la-SDL_ttf.lo -MD -MP -MF .deps/libSDL2_ttf_la-SDL_ttf.Tpo -c ../SDL_ttf.c -o libSDL2_ttf_la-SDL_ttf.o >/dev/null 2>&1
```

Important here is that the command includes `-DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=20 -DSDL_BUILD_MICRO_VERSION=1` (=2.20.1).

Please remove your build directory, and provide the complete output of all commands. Perhaps something is sticking out.

**Comment by fxlevy** [comment]
OK, i deleted the content of the build folder, rerun the configure command and then the make.
Here is the command at moment of the error:

libtool: compile:  gcc -DPACKAGE_NAME=\"SDL2_ttf\" -DPACKAGE_TARNAME=\"SDL2_ttf\" -DPACKAGE_VERSION=\"2.20.0\" "-DPACKAGE_STRING=\"SDL2_ttf 2.20.0\"" -DPACKAGE_BUGREPORT=\"https://github.com/libsdl-org/SDL_ttf/issues\" -DPACKAGE_URL=\"\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=20 -DSDL_BUILD_MICRO_VERSION=0 -DPACKAGE=\"SDL2_ttf\" -DVERSION=\"2.20.0\" -DTTF_USE_HARFBUZZ=1 -DHAVE_CXX11=1 -DALIGNOF_STRUCT_CHAR__=1 -DX_DISPLAY_MISSING=1 -I. -I.. -I../external/freetype/include -DFT2_BUILD_LIBRARY -DFT_PUBLIC_FUNCTION_ATTRIBUTE= -I../external/harfbuzz -I../external/harfbuzz/src -DHAVE_CONFIG_H -DFT_CONFIG_OPTION_USE_HARFBUZZ -g -O2 -D_REENTRANT -I/usr/local/include -I/usr/local/include/SDL2 -Wall -fvisibility=hidden -DHAVE_OPENGL -MT libSDL2_ttf_la-SDL_ttf.lo -MD -MP -MF .deps/libSDL2_ttf_la-SDL_ttf.Tpo -c ../SDL_ttf.c  -fPIC -DPIC -o .libs/libSDL2_ttf_la-SDL_ttf.o

I can see the parameters you mention:
-DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=20 -DSDL_BUILD_MICRO_VERSION=0
But this means 2.20.0 and not 2.20.1

So, I downlloaded the 2.20.0 instead and everything worked smothly!
That was the issue the version parameters in the Makefile are wrong in the 2.20.1 version
they should be 
-DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=20 -DSDL_BUILD_MICRO_VERSION=1
and not
-DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=20 -DSDL_BUILD_MICRO_VERSION=0
Which is correct of course for the 2.20.0 release. :)

May thanks for the help and to solve this issue.

**Comment by madebr** [comment]
I can reproduce the error now.

The `release-2.20.1` tag has updated `configure.ac`, but has not run `./autogen.sh` to regenerate `configure` + `Makefile.in`.

Offending commit: 0a652b598625d16ea7016665095cb1e9bce9ef4f

@slouken Reminder for the next release ;)

**Comment by fxlevy** [comment]
Hello, based on the last feedback of @madebr , can we say we that this issue is solved and close it?

**Comment by madebr** [comment]
I think it's fine to close this one.
Enumerating everything that needs to be done on a release would be too cumbersome.

**Comment by slouken** [comment]
> I can reproduce the error now.
> 
> The `release-2.20.1` tag has updated `configure.ac`, but has not run `./autogen.sh` to regenerate `configure` + `Makefile.in`.
> 
> Offending commit: [0a652b5](https://github.com/libsdl-org/SDL_ttf/commit/0a652b598625d16ea7016665095cb1e9bce9ef4f)
> 
> @slouken Reminder for the next release ;)

Yep, noted, thanks!
