### ISSUE TITLE
CMAKE Having difficulty finding SDL3 built locally

### ISSUE THREAD

**Issue by cnlohr** [libsdl-org/SDL_ttf#261]
If I compile a copy of SDL3 in /data/SDL3/buildlinuxarm64 that works and I can install it with `make install`.  I then check out a copy of `SDL3_ttf` as follows but it gives an error.  I have verified that SDL3Config.cmake is located at the specified location.

```
/data/SDL_ttf/build# cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSDL3TTF_VENDORED=ON -DSDL3TTF_HARFBUZZ=ON -DSDL3_DIR=../../SDL3/buildlinuxarm64 ..
-- Configuring SDL3_ttf 3.0.0
CMake Error at CMakeLists.txt:76 (find_package):
  By not providing "FindSDL3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL3", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL3" (requested
  version 3.0.0) with any of the following names:

    SDL3Config.cmake
    sdl3-config.cmake

  Add the installation prefix of "SDL3" to CMAKE_PREFIX_PATH or set
  "SDL3_DIR" to a directory containing one of the above files.  If "SDL3"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Any idea what command-line parameters I need to pass to cmake to build against a local copy of SDL3?

**Comment by madebr** [comment]
CMake's find procedure is documented [here](https://cmake.org/cmake/help/latest/command/find_package.html#id9).
`SDL3_DIR` is only checked as an environment variable, not as a cmake variable.
You can pass the root of sdl3 with the `SDL3_ROOT` CMake variable, or append it to the `CMAKE_PREFIX_PATH` CMake list.

**Comment by cnlohr** [comment]
That fixed it.

**Comment by cnlohr** [comment]
I am really struggling here. Can you provide what an actual line would look like?  Note that adding `-DSDL3_ROOT=../../SDL3` has no impact from what I can tell, since it's only the `SDL3_DIR` envvar that fixes things. 

It will configure now but I still have this error.
```
# SDL3_DIR=../../SDL3/buildlinuxarm64/ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSDL3TTF_VENDORED=ON -DSDL3TTF_HARFBUZZ=ON -DSDL3_ROOT=../../SDL3 ..
-- Configuring SDL3_ttf 3.0.0
CMake Error at /data/STEAMLINK/streaming_client/SDL3/buildlinuxarm64/SDL3Config.cmake:53 (include):
  include could not find requested file:

    /data/STEAMLINK/streaming_client/SDL3/buildlinuxarm64/sdlfind.cmake
Call Stack (most recent call first):
  CMakeLists.txt:76 (find_package)
```
(It continues to configure)

**Comment by cnlohr** [comment]
If I manually move the `sdlfind.cmake` script to the build directory, it gets a little further, but that also feels wrong.  Should I be pointing cmake to the sdlfind already in the sdl3 tree?

`cp ../../SDL3/cmake/sdlfind.cmake ../../SDL3/buildlinuxarm64/sdlfind.cmake`

And, even if I do that cmake still doesn't know it has `SDL3::SDL3`
```
-- Configuring done
CMake Error at CMakeLists.txt:116 (target_link_libraries):
  Target "SDL3_ttf" links to:

    SDL3::SDL3

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at CMakeLists.txt:340 (target_link_libraries):
  Target "glfont" links to:

    SDL3::SDL3

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at CMakeLists.txt:340 (target_link_libraries):
  Target "showfont" links to:

    SDL3::SDL3

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at CMakeLists.txt:340 (target_link_libraries):
  Target "testapp" links to:

    SDL3::SDL3

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

```

**Comment by madebr** [comment]
Personally, I configure with `CMAKE_PREFIX_PATH`, using an absolute path.
So I usually add `-DCMAKE_PREFIX_PATH=$PWD/relative/path/to/sdl3/prefix`.
The path you add must be the path where you installed sdl3 to, not where you built SDL
[Check sdl3's workflow how we test it.](https://github.com/libsdl-org/SDL/blob/02fbf2cf991bf8310d1a6400abaf05ff5ffff52c/.github/workflows/main.yml#L101-L108]

**Comment by madebr** [comment]
The current SDL cmake script requires you to configure, build and install SDL to make use of `find_package`.
I'll look into allowing use of the cmake files present in the build folder, so you don't need to install

**Comment by cnlohr** [comment]
Do you have to actually install SDL3 to your system?  My issue is my application needs a special version of SDL3 that needs to remain separate from the system version.  I don't have a good grasp on what that process would look like.

**Comment by madebr** [comment]
Use `-DCMAKE_INSTALL_PREFIX=prefix` to install SDL3 to a folder named `prefix`. You can freely move that folder.
You then simply need to pass the full path of this prefix folder as `-DCMAKE_PREFIX_PATH` of sdl3_ttf.

**Comment by madebr** [comment]
I created https://github.com/libsdl-org/SDL/pull/7240 that will allow you to use `find_package(SDL3)` with `-DSDL3_DIR=path/to/SDL3/build/directory`.
It (currently) requires CMake 3.26 because of this (shining new) CMake feature: [`BUILD_LOCAL_INTERFACE`](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:BUILD_LOCAL_INTERFACE).

**Comment by cnlohr** [comment]
This has resolved this portion of the build for me.
