### ISSUE TITLE
CMake error with Could NOT find PrivateSDL2, found suitable version "2.24.1", minimum required is "2.0.10"

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL_ttf#262]
Hi,

I am trying to build the SDL2_ttf 2.20.1 using a FetchContent + add_subdirectory, and I am having an error that I can't quite figure it out what it is:

```
Including SDL_ttf ...
CMake Warning at cmake-build-debug/_deps/sdlttf_content-src/cmake/PrivateSdlFunctions.cmake:55 (message):
  Could not verify SDL2 version.  Assuming SDL2 has version of at least
  2.0.10.
Call Stack (most recent call first):
  cmake-build-debug/_deps/sdlttf_content-src/CMakeLists.txt:74 (sdl_find_sdl2)


-- Configuring SDL2_ttf 2.20.1
-- Using private SDL2 find module
CMake Error at C:/Users/user/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/bin/cmake/win/x64/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PrivateSDL2 (missing: SDL2_LIBRARY) (found suitable version
  "2.24.1", minimum required is "2.0.10")
Call Stack (most recent call first):
  C:/Users/user/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/bin/cmake/win/x64/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake-build-debug/_deps/sdlttf_content-src/cmake/FindPrivateSDL2.cmake:33 (find_package_handle_standard_args)
  cmake-build-debug/_deps/sdlttf_content-src/cmake/PrivateSdlFunctions.cmake:63 (find_package)
  cmake-build-debug/_deps/sdlttf_content-src/CMakeLists.txt:74 (sdl_find_sdl2)
  ```

I have SDL 2.24.1 available in my computer, it's not being fetch but instead it's found using find_package. Any ideas?

I am on Windows 10 and using CMake through CLion 2022.3.2.

Edit: ok, I think I figured it out... in the FindPrivateSDL2.cmake:
https://github.com/libsdl-org/SDL_ttf/blob/0a652b598625d16ea7016665095cb1e9bce9ef4f/cmake/FindPrivateSDL2.cmake#L33-L36

But in SDL2.24.1 there is no `SDL2_LIBRARY`

https://github.com/libsdl-org/SDL/blob/a1d1946dcba6509f0679f507b57e7b228d32e6f8/sdl2-config.cmake.in#L31-L34

ahn... Trying the latest commit in 2.26.x there is no `SDL2_LIBRARY` there either...

Edit: 

adding `set(SDL2_LIBRARY      SDL2::SDL2main SDL2::SDL2)` in my local sdl2-config.cmake fix this issue

I think the proper fix for the time being would be to use `SDL2_LIBRARIES` here in SDL_ttf, to ensure it works with the SDL releases that have existed so far, and then also including `SDL2_LIBRARY` variable in SDL2 `sdl2-config.cmake.in`  (SDL_ttf 2.20.2 and SDL2 2.26.3). And later in another release sync these (SDL_ttf 2.22.0 and SDL2 2.28.0).

**Comment by madebr** [comment]
The `FindPrivateSDL2.cmake` file is a method of last resort to find SDL2: older SDL2 releases don't provide any CMake support.
Because you're using a recent SDL2 that provides a conforming `sdl2-config.cmake`, `FindPrivateSDL2.cmake` should never be reached.

[When building a shared sdl2_ttf library, `SDL2::SDL2` needs to be available. For a static sdl2_ttf library, `SDL2::SDL2-static` needs to be present.](https://github.com/libsdl-org/SDL_ttf/blob/622ccd655e9b0c3298f1b85fe2869e0beca97ea3/CMakeLists.txt#L67-L77)
When you get SDL2 through `FetchContent`, the SDL2 target should already be made present and either fall through or succeed in the first branch.

Can you provide me with a minimal example so I can take a look at it?

**Comment by ericoporto** [comment]
The problem doesn't happen when I build SDL2 through FetchContent, the problem happens when I use SDL2 from the VC release package: https://github.com/libsdl-org/SDL/releases/download/release-2.24.1/SDL2-devel-2.24.1-VC.zip

**Comment by madebr** [comment]
I tried the following on my Windows system with my distro's mingw toolchain:
- Download [SDL2-devel-2.24.1-VC.zip](https://github.com/libsdl-org/SDL/releases/download/release-2.24.1/SDL2-devel-2.24.1-VC.zip) and extract it to `/tmp`
- Run the following command from a subdirectory of SDL_ttf:
    ```
    cmake .. -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -GNinja -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_PREFIX_PATH=/tmp/SDL2-2.24.1/  -DSDL2TTF_VENDORED=ON
    ```
    The `-DCMAKE_PREFIX_PATH=...` is important here. It tells CMake's `find_package` in what places to look.


Also not that the cmake script will not allow you to build a static SDL_ttf library without a static SDL2 library, which the VC development package does not ship.

**Comment by ericoporto** [comment]
> Also note that the cmake script will not allow you to build a static SDL_ttf library without a static SDL2 library

Why?

**Comment by madebr** [comment]
To forbid building a shared SDL2_ttf library with a static SDL2 built-in.

In the reverse case, a static SDL2_ttf can link to both a shared/static SDL2.
But for ease of implementation + reproducibility + no people complaining, the script simply requires SDL2 sharedness == SDL2_ttf sharedness.

**Comment by madebr** [comment]
Not that this limitation only applies when you're building SDL2_ttf yourself.
When you're using already built packages, then you can do whatever you want.

**Comment by ericoporto** [comment]
Sorry, can you point me the code to disable this check? I also need to disable Freetype and Harfbuzz from SDL2_ttf.

**Comment by madebr** [comment]
[This code](https://github.com/libsdl-org/SDL_ttf/blob/622ccd655e9b0c3298f1b85fe2869e0beca97ea3/CMakeLists.txt#L67-L75) shows what to chose.
Add `set(sdl2_target_name SDL2::SDL2)`  after the `endif()`.
Then it will look for `SDL2::SDL2`, instead of a static SDL2.

**Comment by madebr** [comment]
> I also need to disable Freetype and Harfbuzz from SDL2_ttf.

What do you mean by that? `SDL2TTF_VENDORED` switches between system freetype/harfbuzz and vendored versions. `SDL2TTF_HARFBUZZ` allows to disable harfbuzz. But you can't disable freetype. It's essential to parse ttf fonts.

**Comment by ericoporto** [comment]
> Add set(sdl2_target_name SDL2::SDL2) after the endif().

Thanks!

> SDL2TTF_VENDORED switches between system freetype/harfbuzz and vendored versions.

Thanks.

> But you can't disable freetype. It's essential to parse ttf fonts.

I prefer to build both from upstream, but thanks.
