### ISSUE TITLE
It seems that text directions TTB and BTT are reversed

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_ttf#265]
My fellow project member was working on a PR to port SDL_TTFSetFontDirection to Python (https://github.com/pygame-community/pygame-ce/pull/1956), but couldn't figure out why the top to bottom text and bottom to top text were exhibiting the opposite behaviors.

I looked through his code and couldn't find a problem with it, looked through the SDL_ttf.c mapping to harfbuzz direction, couldn't find a problem with that either.

My apologies, I have yet to make a C reproducer script, so I could be mistaken that this is an error here in SDL_ttf.

However, I have a theory- maybe harfbuzz is giving out vertical information in the opposite coordinate system from SDL. Since in SDL, down is +y, whereas in normal grid coordinates up is +y.

**Comment by 1bsyl** [comment]
Also SDL2_ttf : https://github.com/libsdl-org/SDL_ttf/commit/b295578808267053579f0615c20d53a165dff399 
(cc @sezero)

**Comment by Starbuck5** [comment]
Can confirm that this fixes it.

Thanks for such a speedy patch!
