### ISSUE TITLE
Documentation of TTF_OpenFontRW is missing key info

### ISSUE THREAD

**Issue by vivaladav** [libsdl-org/SDL_ttf#267]
I came here to report that _TTF_OpenFontRW_ fails on multiple calls with the same _SDL_RWops_ and requesting a smaller point size than the one(s) requested before, but apparently this is well know since #108 and it's some kind of accepted behavior.

Just as reference for people who might encounter the same issue, this is what happens on multiple calls:

```
SDL_RWops * data;
TTF_OpenFontRW(data, 0, 20);    // OK
TTF_OpenFontRW(data, 0, 22);    // OK
TTF_OpenFontRW(data, 0, 22);    // OK
TTF_OpenFontRW(data, 0, 18);    // ERROR: Couldn't load font file
```
To fix that your code needs to reset the _SDL_RWops_ with _SDL_RWseek_ before calling _TTF_OpenFontRW_.

I am not sure I understand why _TTF_OpenFontRW_ can't call _SDL_RWseek(RWops, 0, RW_SEEK_SET)_ itself, but if that's a design choice it should be documented or people will never have a clue until they find #108 (I didn't while I was trying to figure things out) or try to call _SDL_RWseek_ like I did (but after wasting a lot of time debugging my code and trying other random things).

**Comment by slouken** [comment]
It seems like for SDL_ttf 3.0 we should fix this behavior.
