### ISSUE TITLE
SDL_CreateRGBSurfaceWithFormatFrom is missing in SDL2_tff.dll?

### ISSUE THREAD

**Issue by sjhaverkamp325** [libsdl-org/SDL_ttf#269]
Hello, I'm using ttf 2.20.2 with SDL2 version 2.26.3 and I get a run time error at the start saying "The procedure entry point SDL_CreateRGBSurfaceWithFormatFrom could not be located in the dynamic link library in (projectpath)/SDL2_tff.dll." I'm using Visual Studios if it helps.

**Comment by madebr** [comment]
Googling for the `The procedure entry point xxx could not be located in the dynamic link library` error, I think there are older SDL2.dll('s) on your system.
Copy a recent one (including SDL2_ttf.dll) to the folder(s) where VC is building your .exe.
Also check all entries in your `PATH` environment variable.

**Comment by sjhaverkamp325** [comment]
Yup, found the old sdl2.dll file it was in my windows folder.
