### ISSUE TITLE
SDL-TTF: Wiki-Pages disappeared

### ISSUE THREAD

**Issue by klartext** [libsdl-org/SDL_ttf#270]
I think once there were Wiki-Pages.
They are empty now: https://wiki.libsdl.org/SDL2/SDL_ttf

Please reactivate it.

**Comment by Lundis** [comment]
https://wiki.libsdl.org/SDL2_ttf

**Comment by klartext** [comment]
Thanks.

**Comment by klartext** [comment]
But it's not linked here: https://wiki.libsdl.org/SDL2/Libraries
