### ISSUE TITLE
Why does LCD text rendering change a background colour with 0 alpha (transparent) to opaque?

### ISSUE THREAD

**Issue by MyreMylar** [libsdl-org/SDL_ttf#271]
See these lines here:

https://github.com/libsdl-org/SDL_ttf/blob/76e55783a549839ba96b8aafc6d55c8451f950ce/SDL_ttf.c#L3501-L3503

Was just testing out `TTF_RenderUTF8_LCD_Wrapped()` with a background colour of `SDL_Color backg = {0, 0, 0, 0}` and noticed that I was getting a returned surface of `{0, 0, 0, 255}` - Opaque black. Whereas if I pass in `SDL_Color backg = {0, 0, 0, 1}` I get an _almost_ fully transparent background.

I'm just not sure why this is being done? Is it necessary for one of the other rendering modes and just getting passed though by mistake?

**Comment by 1bsyl** [comment]
I don't remember why. but the code there is common to all text/shaded/blended/lcd. Maybe this make more sense with blended/shaded - and not LCD rendering? maybe blending with alpha == 0 doesn't make sense ?

**Comment by slouken** [comment]
Yeah, that seems silly. :)
