### ISSUE TITLE
`SDL_aligned_alloc` is not declared. The library won't build.

### ISSUE THREAD

**Issue by Redstonerayy** [libsdl-org/SDL_ttf#282]
__Problem__:
I'm using the SDL3 and the SDL_ttf libraries for a project. I cloned both of them as subrepos.
I use CMake as a build system, so I added them as subdirectories. Upon building however Clang fails.
Therefore I can't use the SDL_ttf library, which is unfornate for my goals. 
Is there some proper way to get this to work by changing the build steps?

__What did I do__:
1. Cloned the latest SDL_ttf release at this time ( commit `67837811bee66a23fac30fbab43ed86682f99840` )
2. I added it to my CMakeLists.txt file:
```cmake
CMAKE_MINIMUM_REQUIRED(VERSION 3.17)

project(touren)

set(CMAKE_CXX_FLAGS "-O2 -march=native -std=c++20")

# sdl3
add_subdirectory(SDL)
add_subdirectory(SDL_ttf)

# main project
file(GLOB_RECURSE SOURCE_FILES src/*.cpp)

add_executable(main ${SOURCE_FILES})

target_include_directories(main PRIVATE
    src/graphics
    src/calculation
    src/io
    SDL/include
    SDL_ttf/include
)

target_link_libraries(main SDL3 SDL3_ttf)
```
3. I tried to build it, but it failed.
4. I used the VSCode search feature, but i could not find a definition of the function, i only found this multiple times
`extern DECLSPEC SDL_MALLOC void *SDLCALL SDL_aligned_alloc(size_t alignment, size_t size);`

__System Info__:
```
clang version 15.0.7
cmake version 3.26.2
OS is Linux with 6.2.9-zen1-1-zen Kernel
```
__Compiler Error__:
```
FAILED: SDL_ttf/CMakeFiles/SDL3_ttf.dir/SDL_ttf.c.o 
/usr/bin/clang -DBUILD_SDL -DDLL_EXPORT -DSDL_BUILD_MAJOR_VERSION=3 -DSDL_BUILD_MICRO_VERSION=0 -DSDL_BUILD_MINOR_VERSION=0 -I/home/anton/Github/bwinf2023-runde-2/Aufgabe1-Implementierung/SDL_ttf/include -I/home/anton/Github/bwinf2023-runde-2/Aufgabe1-Implementierung/SDL_ttf/include/SDL3 -I/home/anton/Github/bwinf2023-runde-2/Aufgabe1-Implementierung/build/SDL/include -I/home/anton/Github/bwinf2023-runde-2/Aufgabe1-Implementierung/SDL/include -I/home/anton/Github/bwinf2023-runde-2/Aufgabe1-Implementierung/SDL/include/SDL3 -isystem /usr/include/freetype2 -fPIC -fvisibility=hidden -Wall -Wextra -MD -MT SDL_ttf/CMakeFiles/SDL3_ttf.dir/SDL_ttf.c.o -MF SDL_ttf/CMakeFiles/SDL3_ttf.dir/SDL_ttf.c.o.d -o SDL_ttf/CMakeFiles/SDL3_ttf.dir/SDL_ttf.c.o -c /home/anton/Github/bwinf2023-runde-2/Aufgabe1-Implementierung/SDL_ttf/SDL_ttf.c
/home/anton/Github/bwinf2023-runde-2/Aufgabe1-Implementierung/SDL_ttf/SDL_ttf.c:1454:14: warning: call to undeclared function 'SDL_aligned_alloc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    pixels = SDL_aligned_alloc(alignment + 1, size);
             ^
/home/anton/Github/bwinf2023-runde-2/Aufgabe1-Implementierung/SDL_ttf/SDL_ttf.c:1454:12: error: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
    pixels = SDL_aligned_alloc(alignment + 1, size);
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/anton/Github/bwinf2023-runde-2/Aufgabe1-Implementierung/SDL_ttf/SDL_ttf.c:1461:9: warning: call to undeclared function 'SDL_aligned_free'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        SDL_aligned_free(pixels);
        ^
2 warnings and 1 error generated.
```

**Comment by madebr** [comment]
I don't see anything standing out.
SDL3 currently does not have a `SDL3` target, so you need to link to `SDL3::SDL3`, `SDL3::SDL3-shared` or `SDL3::SDL3-static` instead.

I ijust tried to build  current SDL3_ttf, with `-DCMAKE_C_FLAGS="-Wimplicit-function-declaration"`, but don't see a warning/error.
Can you please verify you're building with the tip of the `main` branches? And if the problem remains, tell us what commits you've checked out?

**Comment by Redstonerayy** [comment]
thanks for pointing out the mismatch in my Cmake file and if i may not have checked my commit version. i checked and updated my SDL3 submodule. now, when linking against SDL3::SDL3 it works. seems the function was just not included in my outdated local SDL3 version. it works now
