### ISSUE TITLE
Rendering onto a previously allocated surface

### ISSUE THREAD

**Issue by takase1121** [libsdl-org/SDL_ttf#283]
Can I avoid creating a new surface when using SDL_ttf by providing my own?

**Comment by 1bsyl** [comment]
no, SDL_ttf creates the surfaces

**Comment by ivan-mogilko** [comment]
I apologize for necro-posting in this old issue, but could someone explain why this library is designed to created a new surface when rendering a text, and why there's no alternate function that would accept a precreated surface as a parameter to draw upon?

**Comment by takase1121** [comment]
> I apologize for necro-posting in this old issue, but could someone explain why this library is designed to create a new surface each time when rendering a text, and why there are no alternate functions that would accept a precreated surface as a parameter to draw upon?

My guess is that the library expects a certain surface format when copying bitmap data. Other than that some surface formats can have weird pixel alignments that will require conversion anyway.

**Comment by slouken** [comment]
> could someone explain why this library is designed to create a new surface each time when rendering a text, and why there are no alternate functions that would accept a precreated surface as a parameter to draw upon?

There is now an alternate function to do this: [TTF_DrawSurfaceText](https://wiki.libsdl.org/SDL3_ttf/TTF_DrawSurfaceText)

**Comment by ericoporto** [comment]
@slouken is that only in SDL_ttf SDL 3 branch or is it also in the SDL2 branch?
