### ISSUE TITLE
In Visual Studio projects SDL_ttf.h is not directly accessible

### ISSUE THREAD

**Issue by PurityLake** [libsdl-org/SDL_ttf#290]
This is a rather small issue but when using the Visual Studio projects, when you attempt to open `SDL_ttf.h` it complains that the file does not exists.

This is just a configuration problem so it is an easy fix.

**Comment by madebr** [comment]
Fixed by #291. Thanks again!

**Comment by sezero** [comment]
Fixed by https://github.com/libsdl-org/SDL_ttf/pull/291 ?

**Comment by sezero** [comment]
> Fixed by #291 ?

Was too late :)

**Comment by madebr** [comment]
I :gun:  first :P
