### ISSUE TITLE
Bitmap font spacing incorrect when using Harfbuzz

### ISSUE THREAD

**Issue by tilderain** [libsdl-org/SDL_ttf#299]
The kerning is ok when using normal font style, but on bold it doesn't switch to the bold spacing and sticks to the normal spacing instead.

Non-harfbuzz:
![2023-07-31_19-19-53](https://github.com/libsdl-org/SDL_ttf/assets/7954485/df621b6d-1647-4adc-877e-2d2cfb483bd1)

Harfbuzz:
![2023-07-31_19-19-38](https://github.com/libsdl-org/SDL_ttf/assets/7954485/438d0581-9084-4583-9cc3-32a52f86826a)

**Comment by slouken** [comment]
@1bsyl, do you want to take a look at this?

**Comment by 1bsyl** [comment]
yes, here's some fix I guess: #301 
@tilderain can you try it ?

**Comment by tilderain** [comment]
Wonderful, it's fixed now.
