### ISSUE TITLE
add a function to select the char map

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#32]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [C source of SelectCharMap (SelectCharMap.c, application/octet-stream, 2013-07-10 04:43:03 +0000, 704 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1216)

**Reported in version:** 2.0.11
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2013-07-10 04:43:03 +0000, Matthias Kievernagel wrote:

> Created attachment 1216
> C source of SelectCharMap
> 
> See discussion on the forum:
> http://forums.libsdl.org/viewtopic.php?t=9228
> 
> As noted there, I guess error handling has to be changed
> to suit library style.
> Currently, it returns 0 for "no error, charmap changed successfully"
> and 1 for "error, invalid parameter or charmap not found".
> 
> Regards,
> Matthias Kievernagel

On 2017-09-10 05:43:33 +0000, Sam Lantinga wrote:

> This is a good idea, and is on the list for a future release.

**Comment by slouken** [comment]
We've added harfbuzz support, which has much richer support for different scripts. SDL_ttf 3.0 also has the ability to get the font face directly if you want low level access for things like this, so I'll go ahead and close this for now.
