### ISSUE TITLE
FreeType version update?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL_ttf#332]
The latest release of FreeType is 2.13.2, should we update our pinned version for the SDL_ttf release?

**Comment by slouken** [comment]
Yes. I'll do another RC build once you've updated the FreeType version.

**Comment by sezero** [comment]
Upgrade is done, closing.

**Comment by sezero** [comment]
@slouken: Your 2.21.2 prerelease tarball still has the old freetype 2.13.0 in it. Something is still broken.

**Comment by slouken** [comment]
Investigating...

**Comment by sezero** [comment]
... binaries most likely have the old version built in, too..

**Comment by slouken** [comment]
Ironically, the binaries were built with the updated version. I'm uploading fixed archives now. Thanks for the catch!

**Comment by slouken** [comment]
Done!

**Comment by sezero** [comment]
> Ironically, the binaries were built with the updated version. I'm uploading fixed archives now. Thanks for the catch!

To make sure, `TTF_GetFreeTypeVersion()` returns the correct version, yes?

**Comment by slouken** [comment]
Yes.
