### ISSUE TITLE
Enabling/disabling kerning not having any impact on rendering

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_ttf#339]
Hello, one of the pygame-ce members was working on porting SDL_ttf's `TTF_SetFontKerning` function to pygame-ce's font module (https://github.com/pygame-community/pygame-ce/pull/2718), but we noticed that it didn't seem to have any impact on the text, in all the fonts we tried. I tried arial, times new roman, freesansbold, cascadia mono, a couple other things from my system.

Looking into the source, I noticed `font->use_kerning` is only used in non-harfbuzz code paths. I looked into how to enable/disable kerning in harfbuzz, and I found that `hb_shape` can take an array `hb_feature_t`s that adjust their default features. I'll send a PR for this for SDL2 and SDL3. (I wanted to open an issue as well so there's a record in the issues tab, and in case my solution doesn't work for some reason).

**Comment by slouken** [comment]
Looks good, thanks!
