### ISSUE TITLE
Text is shifted off-center when wrapped using TTF_WRAPPED_ALIGN_CENTER

### ISSUE THREAD

**Issue by Marmotus** [libsdl-org/SDL_ttf#350]
Hello! I've been enjoying my time using SDL a bunch and just noticed something that is causing me a slight issue. It seems like spaces are left over when text is wrapped, causing the text to be shifted a bit off-center. I've attached two images that hopefully demonstrate what I mean. The first one is when the text is too short to wrap, and the second one is when the text has been wrapped.

![Example 1](https://github.com/libsdl-org/SDL_ttf/assets/43265463/178778ca-7336-4928-89aa-8e24b1c57fc9)

![Example 2](https://github.com/libsdl-org/SDL_ttf/assets/43265463/57d7c827-7f7c-4eb1-ae2d-aafacf1c07f1)

Would it be possible to change this behavior to trim trailing spaces like that?

Thank you all for the great library, by the way. 🙏😁

**Comment by slouken** [comment]
@1bsyl, can you look at this?

**Comment by slouken** [comment]
> @1bsyl, can you look at this?

Actually, I have a handle on this as part of some other work that I'm doing. Never mind! :)

**Comment by slouken** [comment]
This is fixed for SDL_ttf 3.0. Please let me know if you run into any issues with it!
