### ISSUE TITLE
Can't make: No rule to make target 'external/freetype/src/autofit/autofit.c'.

### ISSUE THREAD

**Issue by Sarthak-Wd** [libsdl-org/SDL_ttf#352]
Sorry if this is not the place. But how do I install this? Here is what I had tried:
./configure
make

At first I was getting problems for the headers ft2build.h and hb.h. I updated the C_INCLUDE_PATH variable and those went away. Now, the build process runs for a while, but then stops with this:

make: *** No rule to make target 'external/freetype/src/autofit/autofit.c', needed by 'external/freetype/src/autofit/libSDL2_ttf_la-autofit.lo'.  Stop.

**Comment by madebr** [comment]
By default, the configure script uses a builtin freetype and harfbuzz.
You need to run the [`download.sh`](https://github.com/libsdl-org/SDL_ttf/blob/main/external/download.sh) script to download these.
Or when you're using the git repo, fetch them using git submodules.

System freetype and harfbuzz libraries can be used instead by configuring with `--disable-freetype-builtin --disable-harfbuzz-builtin`.
