### ISSUE TITLE
macOS with Brew - "fatal error: 'SDL.h' file not found" when including <SDL2/SDL_ttf.h> as a header

### ISSUE THREAD

**Issue by mattmaniak** [libsdl-org/SDL_ttf#361]
I am unable to compile a code with SDL2_ttf (2.22.0) header included. It is installed via Brew. SDL2 version is 2.30.3.

Repro steps:
1. Ensure you have Brew installed (https://brew.sh).
2. Install SDL2 2.30.3 via Brew: `brew install sdl2@2.30.3`.
3. Instal SDL2_ttf 2.20.0 via Brew: `brew install sdl2_ttf@2.22.0`.
4. Create an example header file that imports SDL TTF lib, eg. `ttf_included.h`:
```
#include <SDL2/SDL_ttf.h>
```
5. Try to compile it via:
```
gcc ttf_included.h -I /opt/homebrew/Cellar/sdl2_ttf/2.22.0/include
```
6. The outcome is an error:
```
In file included from ttf_included.h:1:
/opt/homebrew/Cellar/sdl2_ttf/2.22.0/include/SDL2/SDL_ttf.h:39:10: fatal error: 'SDL.h' file not found
#include "SDL.h"
         ^~~~~~~
1 error generated.
```

**Comment by madebr** [comment]
SDL2_ttf's headers depend on SDL2's headers, so you need to add the include path of SDL2 as well.

**Comment by mattmaniak** [comment]
Changing the source file to
```
#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
```

and command to
```
gcc ttf_included.h -I /opt/homebrew/Cellar/sdl2/2.30.3/include -I /opt/homebrew/Cellar/sdl2_ttf/2.22.0/include
```

produces the same issue.

**Comment by mattmaniak** [comment]
Thanks! `-I /opt/homebrew/Cellar/sdl2/2.30.3/include/SDL2` did the job.
