### ISSUE TITLE
Error: sdl_ttf has been disabled because it is deprecated upstream!

### ISSUE THREAD

**Issue by st203** [libsdl-org/SDL_ttf#367]
I get the error message in the title when running brew install sdl_ttf.

Should I use an alternative library? 

Thanks for your help.

**Comment by madebr** [comment]
[sdl_ttf](https://formulae.brew.sh/formula/sdl_ttf#default) is disabled, but [sdl2_ttf](https://formulae.brew.sh/formula/sdl2_ttf#default) isn't.

**Comment by st203** [comment]
Thanks. I'm closing.
