### ISSUE TITLE
Fonts render differently with SDL3.

### ISSUE THREAD

**Issue by mold-boy** [libsdl-org/SDL_ttf#369]
The first screenshot is SDL2:

<img width="370" alt="Screenshot 2024-07-12 at 3 51 47 PM" src="https://github.com/user-attachments/assets/f60bf14a-b18c-4950-a468-43cdb26e4c79">

The second screenshot is SDL3:

<img width="394" alt="Screenshot 2024-07-12 at 3 51 22 PM" src="https://github.com/user-attachments/assets/8d72c220-db10-4ba2-8a94-fabc0af9982f">

**Comment by slouken** [comment]
Can you attach a test program and the fonts you're using?

**Comment by mold-boy** [comment]
I wrote a test program and it rendered perfect with SDL2 and SDL3. I review the game code and realized this is a SDL_Texture scaling difference between SDL2 and SDL3. We will need to rewrite some of that code to obtain our preferred font sizes.

**Comment by slouken** [comment]
If you're referring to the logical presentation mode differences, we're looking at making SDL3 work like SDL2 again. @icculus signed up for that work. :)

**Comment by slouken** [comment]
This should be fixed in the latest SDL3 code.
