### ISSUE TITLE
SDL2 Cmake not finding freetype

### ISSUE THREAD

**Issue by TheSevenSages** [libsdl-org/SDL_ttf#370]
I'm using the cmake files provided with the SDL_ttf download 2.22.0 to link SDL2 to my custom game engine. But when adding the SDL libraries to my executable using the add_subdirectory function my system tells me that I need to go install freetype. I thought that SDL_ttf included freetype for portability?

**Comment by TheSevenSages** [comment]
[message.txt](https://github.com/user-attachments/files/16272800/message.txt)

**Comment by madebr** [comment]
Reading your log, it is actually configuring SDL2_ttf's vendored libfreetype, but fails to read `external/freetype/builds/unix/configure.raw`.

```
CMake Error at src/ThirdParty/SDL2_ttf-2.22.0/external/freetype/CMakeLists.txt:171 (file):
  file STRINGS file
  "C:/Users/trump/Documents/Wolverine-Engine/src/ThirdParty/SDL2_ttf-2.22.0/external/freetype/builds/unix/configure.raw"
  cannot be read.
```
[The file is ascii](https://github.com/libsdl-org/freetype/blob/master/builds/unix/configure.raw).

I just verified SDL2_ttf 2.22.0's [tarball](https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.22.0/SDL2_ttf-2.22.0.tar.gz) and the file is present.

**Comment by madebr** [comment]
Reading this [CMake issue](https://gitlab.kitware.com/cmake/cmake/-/issues/23318), and [this code or origin](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.22.3/Source/cmFileCommand.cxx#L442-443), perhaps the file does not exist on your system or there is a permissions problem?

Remove everything, and extract SDL2_ttf again. Eventually to another directory and do `add_subdirectory("C:/tmp/SDL2_ttf-2.22.0" SDL2_ttf)` instead.

**Comment by TheSevenSages** [comment]
Figured out this issue, I was needing to set the SDL2TTF_VENDORED cmake variable to true before adding the subdirectory. I was having the same problem with SDL2 Mixer, where I needed to set the SDL2MIXER_VENDORED variable to true and then download all of the external libraries/packages into my project by running the "download.sh" file in the "externals" folder.
