### ISSUE TITLE
UNICODE_BOM_NATIVE, UNICODE_BOM_SWAPPED not in library namespace

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL_ttf#371]
While packaging a snapshot in Debian I noticed that when man pages are enabled, this library installs `UNICODE_BOM_NATIVE(3)`, which isn't in the SDL or `TTF_` namespace and seems likely to conflict with other packages.

Looking at the header file, there's also `UNICODE_BOM_SWAPPED` (which is undocumented, therefore no man page).

Are these needed in the public API of the library, or are they only useful internally?

If they should be public API, could they be renamed to `TTF_UNICODE_BOM_NATIVE` and `TTF_UNICODE_BOM_SWAPPED` to bring them into the library's namespace?

**Comment by slouken** [comment]
I plan to remove this for the SDL_ttf 3.0 update, thanks!
