### ISSUE TITLE
Installs a man page for _TTF_Font(3type)

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL_ttf#372]
When API documentation (manual pages) is enabled, wikiheaders sees

```
typedef struct _TTF_Font TTF_Font;
```

and generates a `_TTF_Font` man page. This seems probably unintended.

Am I correct to think that SDL's coding style is to make the struct tag be the same name as the typedef, more like this?

```
typedef struct TTF_Font TTF_Font;
```

Or, wikiheaders could assume that symbols starting with an underscore are meant to be private and ignore them.

**Comment by smcv** [comment]
Similarly libsdl-org/SDL_mixer installs `_Mix_Music.3type`.

**Comment by slouken** [comment]
Fixed, thanks!
