### ISSUE TITLE
Errors when building from source on aarch64 Linux

### ISSUE THREAD

**Issue by CorruptVoidSoul** [libsdl-org/SDL_ttf#405]
I'm building the SDL3 versions of the libraries I want to use on an odd aarch64 Ubuntu system.
If you know about Termux, you'll understand what I mean if I say it's an Ubuntu proot.

I don't know anything about how this works, so I'll just drop the logs here

Don't be surprised if I don't answer right away, it's 9pm and I gotta sleep

[sdl ttf errors.txt](https://github.com/user-attachments/files/17283480/sdl.ttf.errors.txt)

**Comment by slouken** [comment]
@1bsyl, @madebr I believe these are the build errors which resulted in NEON being disabled. Maybe we can do a configure-time check for these?

**Comment by wn2000** [comment]
I'm building on an arm32 platform and got a similar error, except the "expected" and actual types are reversed.

So in @CorruptVoidSoul 's build log (aarch64):
```
arm_neon.h:25579:1: note: expected ‘uint8x16_t’ but argument is of type ‘uint32x4_t’
```

In my case (arm32):
```
arm_neon.h:13946:39: note: expected ‘uint32x4_t’ but argument is of type ‘uint8x16_t’
```

So it seems NEON was enabled in both cases, but somehow arguments meant for aarch64 were passed in arm32 build, and arguments meant for arm32 were passed in aarch64 build.

**Comment by wn2000** [comment]
ps: I got a similar error when building sdl3 and had to disable arm neon to pass that.

**Comment by slouken** [comment]
I believe @madebr is working on CMake detection for this. Good to know it's needed in SDL as well, thanks!

**Comment by madebr** [comment]
I haven't started looking into this, but a problematic toolchain + cmake toolchain file + configure options would be useful.
Ideally, a toolchain from https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

**Comment by jsm174** [comment]
> ps: I got a similar error when building sdl3 and had to disable arm neon to pass that.

Thanks, I was having the same issue as well, and was able to add `-DCMAKE_C_FLAGS="-U__ARM_NEON"` as a workaround until this gets resolved.

```
cmake \
   -DBUILD_SHARED_LIBS=ON \
   -DSDLTTF_SAMPLES=OFF \
   -DSDLTTF_VENDORED=ON \
   -DSDLTTF_HARFBUZZ=ON \
   -DSDL3_DIR=../SDL3-3.1.3/build \
   -DCMAKE_C_FLAGS="-U__ARM_NEON" \
   -DCMAKE_BUILD_TYPE=Release \
   -B build
```

**Comment by madebr** [comment]
I could reproduce this with the "arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu" toolchain from the arm website.
#409 fixes it for me.
