### ISSUE TITLE
restrict keyword doesn't compile in Visual Studio

### ISSUE THREAD

**Issue by sabdul-khabir** [libsdl-org/SDL_ttf#408]
[SDL_hashtable.c](https://github.com/libsdl-org/SDL_ttf/blob/main/src/SDL_hashtable.c) does not compile in Visual Studio 2022

Same issue addressed in https://github.com/libsdl-org/SDL/commit/ff834f77333d2dfad3392bc81887b272c16661d2

**Comment by sezero** [comment]
Fixed. Thanks.
