### ISSUE TITLE
Issues finding freetype.

### ISSUE THREAD

**Issue by cnlohr** [libsdl-org/SDL_ttf#410]
When building on ARM64 debian, if I install 

```sh
sudo apt-get install libfreetype-dev libfreetype6 libfreetype6-dev
```

I can validate the installation with the following:
```
pkg-config --cflags freetype2 
-I/usr/include/freetype2 -I/usr/include/libpng16
```

But when I try to run cmake, I get the following:
```sh
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSDL3TTF_HARFBUZZ=ON -DSDL3TTF_VENDORED=ON   ..
-- Configuring SDL3_ttf 3.0.0
-- SDL3_ttf: Using system freetype library
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY) (found version
  "2.10.4")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindFreetype.cmake:157 (find_package_handle_standard_args)
  CMakeLists.txt:265 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/[...]/SDL_ttf/build/CMakeFiles/CMakeOutput.log".
```

But nothing in the CMakeOutput.log file contains freetype, ft, etc...

Any idea what is going on here or how to resolve the issue?

**Comment by slouken** [comment]
Did you run external/download.sh to get the vendored libraries?

**Comment by slouken** [comment]
SDL_ttf provides it's own copies of those libraries and builds them into SDL_ttf.

**Comment by cnlohr** [comment]
I tried setting `-DSDLTTF_FREETYPE_VENDORED=ON` to no avail.

**Comment by slouken** [comment]
Oh, try this:
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSDLTTF_HARFBUZZ=ON -DSDLTTF_VENDORED=ON   ..`

**Comment by cnlohr** [comment]
`SDLTTF` vs `SDL3TTF`  

That was it.
