### ISSUE TITLE
Bug: Text drawn with a renderer text engine sometimes becomes distorted 

### ISSUE THREAD

**Issue by JBetz** [libsdl-org/SDL_ttf#419]
I haven't find a reliable way to reproduce this yet, but basically, text sometimes becomes distorted when there are multiple text objects drawn to the same window using the same text engine.

With `SDL_RENDER_DRIVER` set to `gpu`, the text in the editor is clear but the text in the grid items has some seemingly random artifacts, most notable between the `t` and `e` glyph inside `Paste`:

![image](https://github.com/user-attachments/assets/9603a585-9d37-4bc0-abc2-933d0d3ceba3)

With `SDL_RENDER_DRIVER` set to `software`, the text in the grid items is noticeably clearer:

![image](https://github.com/user-attachments/assets/863058af-b602-441e-a524-a19c5bf28d0c)

Note however that in both cases the rectangle is slightly narrow, which makes me think that this isn't an issue with the GPU renderer but something in the TTF + renderer interface. Or perhaps wrong usage of the text engine on my side.

**Comment by JBetz** [comment]
No issue drawing multiple text objects created by the same text engine with different colors:
![image](https://github.com/user-attachments/assets/0a329857-736a-4112-be93-97315459989b)

**Comment by slouken** [comment]
The blurriness should be fixed in https://github.com/libsdl-org/SDL_ttf/commit/3adac8ac7ca3be6a5f73a23d930c9f7449f99189.

**Comment by slouken** [comment]
Are you setting a clip rectangle or anything? I'm not sure why it would work in the editor, but not in your button.

**Comment by JBetz** [comment]
I am, and indeed that's probably the issue.

My rectangles have float coordinates when then get truncated to integers to create a `SDL_Rect` when clipping. For static text, the origin is determined by a layout engine which returns `float`s, and then the extent is calculated with `TTF_GetTextSubStringsForRange` which returns `int`s.

I'll need to play with it some more because even if I round `x` and `y` down and `width` and `height` up for the clip rectangle, it still doesn't quite fit.

FWIW, I noticed that if I round the `x` and `y` parameters (i.e., convert from `float` to `int`), the artifacts go away: 

![image](https://github.com/user-attachments/assets/cb2ea786-d21e-42b0-8bbe-34bd0d194cdb)

I haven't tested your fix yet but will soon.

**Comment by slouken** [comment]
Yeah, you shouldn't clip the text. Try removing that and grabbing the latest fix, it should work correctly now.

**Comment by JBetz** [comment]
Blur and artifacts are gone, but now some of the glyphs have bits missing. Oddly, the `e` in the north east slot looks fine while all the others don't.

![image](https://github.com/user-attachments/assets/3449f82f-3e3d-481d-8140-f2eb9c6dead2)

**Comment by JBetz** [comment]
If I truncate the `x` and `y` parameters passed to `TTF_DrawRendererText`, it looks perfect: 

![image](https://github.com/user-attachments/assets/07fca258-07d1-4d1c-b34b-f0e8e83598f2)

**Comment by slouken** [comment]
Yeah, since the text is pixel perfect, it should be drawn on pixel boundaries. We don't mess with the coordinates passed in, because there might be scaling applied, but you want it aligned with the output.

**Comment by JBetz** [comment]
That makes sense. Thanks!
