### ISSUE TITLE
Reimplement Solid text rendering functions.

### ISSUE THREAD

**Issue by CorruptVoidSoul** [libsdl-org/SDL_ttf#423]
I've been migrating the codebase of a pixel game to SDL3 and when it came to SDL3_TTF, I noticed that the Solid functions were gone, and any rendering done with Shaded or Blended really doesn't look good.

I've been told by @slouken to file an issue to get them added back.
Also for those that weren't in the Discord at this moment, here are two images to make a comparison
![SDL2_TTF](https://github.com/user-attachments/assets/2d55c820-b7d9-4a72-8f63-ac127bd8ddac)
![SDL3_TTF](https://github.com/user-attachments/assets/1aaa4339-c515-4f09-8b74-26fc3630a49f)

**Comment by slouken** [comment]
Done!
