### ISSUE TITLE
Memory leak when using TTF_CreateText

### ISSUE THREAD

**Issue by bmrhoads** [libsdl-org/SDL_ttf#425]
I'm having an issue with this and I've isolated it to a simple project with a main like so 

```
#include <SDL3/SDL.h>
#include <SDL3_ttf/SDL_ttf.h>

int main(int argc, char *argv[]) {
  int sdlVer = SDL_GetVersion();
  SDL_Window *window = 0;
  SDL_Renderer *renderer = 0;
  SDL_CreateWindowAndRenderer("Test", 900, 500, SDL_WINDOW_RESIZABLE, &window, &renderer);

  TTF_Init();
  TTF_TextEngine *engine = TTF_CreateRendererTextEngine(renderer);
  TTF_Font *font = TTF_OpenFont("dogica.ttf", 12);

  while (1) {
    TTF_Text *text = TTF_CreateText(engine, font, "Testing", sizeof("Testing"));
    SDL_RenderClear(renderer);
    TTF_DrawRendererText(text, 100, 100);
    SDL_RenderPresent(renderer);
    TTF_DestroyText(text);
  }

  TTF_CloseFont(font);
  TTF_DestroyRendererTextEngine(engine);
  TTF_Quit();
  SDL_DestroyWindow(window);
  SDL_Quit();

  return 0;
}
```

This process of creating the TTF_Text pointer and then destroying it seems to still leave something allocated because the memory grows at ~1MB a second. Maybe I'm misunderstanding something about how CreateText is meant to be used, I'm not sure.

This is on the newest build of the main branch

**Comment by slouken** [comment]
I believe that should work. I'll double check.

**Comment by captain0xff** [comment]
It may be unrelated but one thing I can spot is that sizeof("Testing") will include the null character, you probably don't want that.

**Comment by bmrhoads** [comment]
Oh you're right, I should use strlen since CreateText appends the null terminator. I did notice that DestroyEngineText is not firing since these are new Text instances and needs_layout_update is always false. Could it be that the engine->user_data is not being destroyed when the text is destroyed?

**Comment by slouken** [comment]
Fixed!
