### ISSUE TITLE
Problem detecting SDL3 during SDL_ttf compilation

### ISSUE THREAD

**Issue by rjopek** [libsdl-org/SDL_ttf#428]
Hi!
I encountered an issue while trying to compile `SDL_ttf` with SDL3 as a submodule in my project. Below is a detailed description of the problem and the solution that allowed me to proceed with the compilation.

#### Steps to Reproduce:
1. I set up SDL3 as a submodule in my project and built it in the `SDL/build` directory.
2. I then attempted to configure `SDL_ttf` using `cmake ..` from the `SDL_ttf/build` directory.

#### Expected Behavior:
`CMake` should detect SDL3 via the `SDL3Config.cmake` file, generated during the SDL build in the `SDL/build` directory, and configure `SDL_ttf` without errors.

#### Actual Behavior:
The following error was encountered:
```
CMake Error at CMakeLists.txt:92 (find_package):
  By not providing "FindSDL3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL3", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL3" (requested
  version 3.1.5) with any of the following names:

    SDL3Config.cmake
    sdl3-config.cmake

  Add the installation prefix of "SDL3" to CMAKE_PREFIX_PATH or set
  "SDL3_DIR" to a directory containing one of the above files.
```
#### Solution That Worked:
Setting the `CMAKE_PREFIX_PATH` variable helped resolve the issue and allowed `CMake` to find SDL3:
```
export CMAKE_PREFIX_PATH=../../SDL/build
```
After setting this variable, I was able to proceed with the `SDL_ttf` configuration and compile the project successfully.

#### Additional Information:
During compilation, I encountered one additional warning related to a signed-unsigned comparison in `SDL_ttf.c` at line 3890:

```
SDL_assert(cluster->offset == length);
```
The compiler warning was as follows:

```
comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
```
It might be worth considering an update to this part of the code to avoid potential issues in future versions.

**Comment by madebr** [comment]
CMake uses [this search procedure](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure) for locating dependencies.

I think (untested), you should set `SDL3_DIR` to `SDL/build` prior to configuring SDL_ttf.

**Comment by rjopek** [comment]
It seems inconsistent that SDL3 itself builds without requiring these extra configurations, while SDL_ttf cannot find the same package without additional CMake path settings. Since SDL3 is already available locally within the repository, it would be more convenient if CMake could detect it automatically in submodule setups.

**Comment by madebr** [comment]
You were building an SDL3 application before needing SDL3_ttf, so you already have to build SDL3.
All of SDL3_image, SDL3_mixer, SDL3_net, SDL3_ttf and SDL3_rtf depend on SDL3.
You don't want to rebuild SDL3 for all of them.
You should bring your own.

It might be more convenient for you to not have to tell CMake where you built SDL3,
but it won't work for linux package managers, projects vendoring SDL3, etc

It simply does not scale if every project would need to build every possible dependency.
