### ISSUE TITLE
Issues with SDL_RenderText_Solid_Wrapped only with SDL3

### ISSUE THREAD

**Issue by CorruptVoidSoul** [libsdl-org/SDL_ttf#431]
There are two problems, one, SDL3_ttf doesn't wrap on newline characters, while SDL2_ttf does, two, on Windows, there's a font conversion error and the GDB backtrace told me to report this as a bug

The function is called via a wrapper

```
SDL_Surface* rendertext(TTF_Font* font, char* text, SDL_Color color)
{
	#ifdef SDL2
	return TTF_RenderText_Solid_Wrapped(font, text, color, 0);
	#endif
	#ifdef SDL3
	return TTF_RenderText_Solid_Wrapped(font, text, strlen(text), color, 0);
	#endif
}
```

![oh hecc](https://github.com/user-attachments/assets/522593d5-e0f9-44e2-9f0b-53a2fc2f7d99)

**Comment by slouken** [comment]
Are you still seeing the non-wrapping issue? If so, can you add a code snippet with a C string that reproduces the issue?

I tried using showfont with this string, and it wrapped just fine:
"The quick brown fox\njumped over the lazy dog"

The conversion issue appears to be a bug in gdb, it looks like it's trying to convert 'TTF_Font' in the display and failing for some reason. That error message isn't in SDL_ttf.

**Comment by CorruptVoidSoul** [comment]
I updated my libs today, yes it still happens.
I'm going to share the code that does stuff with screenshots.

The wrapper, slightly changed because giving it 0 also works
`SDL_Surface* rendertext(TTF_Font* font, char* text, SDL_Color color)
{
	#ifdef SDL2
	return TTF_RenderText_Solid_Wrapped(font, text, color, 0);
	#endif
	#ifdef SDL3
	return TTF_RenderText_Solid_Wrapped(font, text, 0, color, 0);
	#endif
}`

The text creation function :
`void createcolortextsprite(SDL_Texture **result, char *text, TTF_Font *font, Position *position, SDL_Color color)
{
	if (*result != NULL) //if the result already points to something, free it before reusing.
	{
		deallocate(*result, VAR_SDL_Texture);
	}
	SDL_Surface *surface = NULL;
	surface = rendertext(font, text, color);
	if (surface == NULL)
	{
		char message[3000];
		strcpy(message, text);
		strcat(message, " could not be written.\nThe program could segfault at any moment.\n");
		strcat(message, SDL_GetError());
		SDL_ShowSimpleMessageBox(0, "Skill issue (text sprite creation).", message, NULL);
	}
	else
	{
		*result = SDL_CreateTextureFromSurface(renderer, surface);
		deletesurface(surface);
		if (*result == NULL)
		{
			SDL_ShowSimpleMessageBox(0, SDL_GetError(), "And this is at this moment that he knew...\nSDL_CreateTextureFromSurface messed up.", NULL);
		}
		else
		{
			#ifdef SDL3
			SDL_SetTextureScaleMode(*result, SDL_SCALEMODE_NEAREST);
			#endif
			gettexturesize(*result, &position->w, &position->h);
			registervariable(*result, VAR_SDL_Texture);
		}
	}
}`

I usually don't pass everything and create my text with this
`void createtextsprite(SDL_Texture **result, char *text, TTF_Font *font, Position *position)
{
	createcolortextsprite(result, text, font, position, white);
}`

The strings, and what happens for each.
`createtextsprite(&optionstext, "Effects\nPinch\n\nReturn\nQuit", ynoverworldfont, &positiontext);
`
![Screenshot_20241209-205239](https://github.com/user-attachments/assets/767427ff-a8f7-4b49-b1cc-661b65d39cb0)

warning, wall of text

`createtextsprite(&explanations, "1.Enter a door in the Nexus\n2.Find an effect\n3.Unlock access to the boss with it\n4.Defeat the boss to get a new effect\n5.Unlock a new area with this effect\n6.Repeat.\n \nPress X to use the current effect\nPress 9 or use the Pinch option to\nteleport to your room\nYou can save by interacting with\nyour desk\nCollect all effects to break free", determinationfont, &positionexplanations);
`
![Screenshot_20241209-205259](https://github.com/user-attachments/assets/a781314a-452c-4e8f-a935-2ee861db0db6)

**Comment by CorruptVoidSoul** [comment]
Indentation was completely destroyed by GitHub, I'm sorry...

**Comment by slouken** [comment]
Fixed, thanks!
