### ISSUE TITLE
I cannot build sdl_ttf on windows

### ISSUE THREAD

**Issue by ChedRed** [libsdl-org/SDL_ttf#432]
The current problem is that when I try to build SDL3_ttf with the vendored libraries (FreeType and HarfBuzz), it simply creates a bunch of windows PowerShell processes that do nothing.

I used `cmake .. -G "MinGW Makefiles" -DSDLTTF_VENDORED=ON` to configure it and `make` to build it. As I write this, it is taking up ram and not making any progress.

![{E80F2EF6-2D0E-4FC4-9B0C-B4767F4B0C90}](https://github.com/user-attachments/assets/41e730fb-9efe-4bd9-9076-59b899d0f985)

**Comment by madebr** [comment]
What does `make VERBOSE=1` show?
Can you see in the task manager (eventually process explorer) what the child processes do and who spawned them?
Can you build other projects with this toolchain?

**Comment by madebr** [comment]
That last command is executing your clang compiler.
Install the latest version, and report this issue to the project packaging your toolchain.
This is not a SDL_ttf issue.
