### ISSUE TITLE
Line spacing question

### ISSUE THREAD

**Issue by itzpr3d4t0r** [libsdl-org/SDL_ttf#435]
Hello I'm a pygame-ce contributor, since we use SDL_ttf as our font rendering backend I've noticed (and hope that I'm not missing something) that there's no way to change the spacing bewteen lines in a multiline text scenario.
I've seen that `TTF_FontLineSkip` returns the recommended spacing between lines of text for a font, but is there a way to set this? If not would you ever consider adding it?

Like it's just weird to have the `TTF_FontLineSkip` getter available since SDL_ttf 2.0.12 but having to upgrade to 3.0 just to be able to set it...

Without something to control that, I'd be forced to render multiple texts separately (one per line) and blit that to another surface.

Like take this picture for example, it's using a multiline text with a `Sylfaen` font of size 17 and the spacing feels a bit too much to me:
![image](https://github.com/user-attachments/assets/0923f85e-b4ac-425c-81c8-23b582023557)

**Comment by itzpr3d4t0r** [comment]
An update, I've noticed there's actually a `TTF_SetFontLineSkip` but it's not available until SDL_ttf 3.0.0. Would it be possible to backport it or is the 2.0 version feture complete?

**Comment by slouken** [comment]
Yep, added for the next SDL_ttf release!

**Comment by slouken** [comment]
SDL_ttf 2.24.0 is released!
