### ISSUE TITLE
Will SDL_ttf be a single pair c file and header forever?

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL_ttf#436]
This project is a single C file and header, and is trivial to build if you just copy it in your own project.

Is there any chance it will become something else in the future?

I know this is a hard question, but maybe if people don't think there are newer complex features the situation should be stable.

The reason I ask is I already have libpng, zlib freetype and harfbuzz working, and in zlib and libpng (dependencies of freetype) I already use them elsewhere. But if there's something in the different build systems here that I have to use would be good to know. But overall, biggest question is if it will become a gazillion of c files that requires something more complex to build in the future.

**Comment by slouken** [comment]
It became several C files for SDL_ttf 3.0 (main branch), however it's not that hard to just add those too, as long as you comply with the zlib license.
