### ISSUE TITLE
`TTF_GPUAtlasDrawSequence.xy/uv` un-ergonomic stride behaviour

### ISSUE THREAD

**Issue by Beyley** [libsdl-org/SDL_ttf#438]
```c
float *xy;                              /**< Vertex positions */
int xy_stride;                          /**< Byte size to move from one element to the next element */

...

sequence->xy_stride = sizeof(float) * 2;
sequence->uv_stride = sizeof(float) * 2;

...

const float *xy = (float *)((Uint8 *)sequence->xy + i * sequence->xy_stride);
```

At the moment to use the `xy`/`uv` fields (which are both `float *`), you have to cast it to a `Uint8 *`, then apply the stride (which is in bytes), then cast back to a `float *` to be able to read the value back out.

Given the strides are always constant and always defined as a multiple of `sizeof(float)`, it would make sense for these strides to be changed to be based on values, rather than bytes, as the current API is very error prone, given you have to hot-potato the pointer type.

pinging @captain0xff since you wrote this initially

**Comment by slouken** [comment]
Strides are generally calculated in bytes, since the values might be pointing into structures that are not aligned with the size of a float.

**Comment by slouken** [comment]
@captain0xff, is there a reason this is variable? Should we just document that the xy and uv coordinates are pairs?

**Comment by captain0xff** [comment]
You are right this doesn't need to be a variable at all. This is just wasting memory unnecessarily. We can just document that they are pairs or provide a macro for the strides or do both.

**Comment by captain0xff** [comment]
I will fix this along with the other two issues.

**Comment by captain0xff** [comment]
I have removed the stride parameters and added to the docs that xy/uv are contiguous arrays consisting of a pair of floats. With the current implementation I don't see a need to do add the strides as macros. @slouken what's your opinion on this?

**Comment by slouken** [comment]
> With the current implementation I don't see a need to add the strides as macros. @slouken what's your opinion on this?

Agreed.

**Comment by captain0xff** [comment]
I am making the xy/uv an array of SDL_FPoint because it feels the something like the following is equally error prone and weird
```c
vert.pos = (Vec3){ sequence->xy[2 * i], sequence->xy[2 * i + 1], 0.0f };
// Or
const float *xy = sequence->xy + 2 * i;
vert.pos = (Vec3){ xy[0], xy[1], 0.0f };
```

**Comment by Beyley** [comment]
closing as fixed
