### ISSUE TITLE
`testgputext` doesn't correctly apply vertex offset

### ISSUE THREAD

**Issue by Beyley** [libsdl-org/SDL_ttf#439]
https://github.com/libsdl-org/SDL_ttf/blob/0ad0c2518be948300ed1e133741932f1ba2a4e7b/examples/testgputext.c#L210

That second to last parameter should be the vertex offset (which you calculate by tallying `seq->num_vertices` as you go).

As per 

https://github.com/libsdl-org/SDL_ttf/blob/0ad0c2518be948300ed1e133741932f1ba2a4e7b/include/SDL3_ttf/SDL_ttf.h#L1661

The indices that `testgputext` copies onto the GPU for sequences are indexed into the per sequence `vertices` array, not a global tally of total vertices, so you need to specify the vertex offset in the draw call to correct for that.

**Comment by slouken** [comment]
@captain0xff, can you take a look?

**Comment by Beyley** [comment]
closing as fixed
