### ISSUE TITLE
Clarify the comment about the TTF_Text 'text' member var

### ISSUE THREAD

**Issue by ThrudTheBarbarian** [libsdl-org/SDL_ttf#440]
Just a note to request slightly different wording around the comment in SDL_ttf.h regarding the 'text' member-variable of the TTF_Text structure. It currently says:

```
    char *text;             /**< A copy of the text used to create this text object, useful for layout and debugging. This will be freed automatically when the object is destroyed. */
```

which (at least to me) implies that it's a copy of the data presented when the structure is created, not that it's a maintained value of the structure as the underlying data is modified. Having discounted this because of the comment, I was wracking my brains trying to figure out where the function call was to extract the UTF8 from the TTF_Text structure once the user had finished messing about with it...

**Comment by slouken** [comment]
Thanks for the feedback! Can you suggest better wording?

**Comment by ThrudTheBarbarian** [comment]
Ah, well, when you put me on the spot ... :)

How about:

A maintained copy of the text that this text object represents, useful for layout, debugging and retrieving the UTF8 string after composition. This will be freed automatically when the object is destroyed.

**Comment by slouken** [comment]
I'm not sure how a maintained copy is different from a copy? Maybe the original text, plus some info on when it's updated?

A copy of the UTF8 text-string that this text object represents, useful for layout, debugging and retrieving the UTF8 string after composition. This is updated when TTF_SetTextString() is called and will be freed automatically when the object is destroyed.

**Comment by ThrudTheBarbarian** [comment]
I guess what I'm trying to get across is that it's not static. The original working implies that it's a snapshot in time of when the TTF_Text structure is initialised, but that's not the case - as you add data to the TTF_Text, the ->text member reflects that new state.

It's actively maintained as live data, is what I'm trying to say. That's the difference.

But I'm good with your suggestion there. That covers it too :) Although it doesn't seem necessary to _specifically_ call TTF_SetTextString(), TTF_InsertTextString() will do it too (admittedly, this is probably the same call under the hood :)

**Comment by slouken** [comment]
How about:
A copy of the UTF8 text-string that this text object represents, useful for layout, debugging and retrieving the UTF8 string after composition. This is updated when the text object is modified and will be freed automatically when the object is destroyed.

**Comment by ThrudTheBarbarian** [comment]
Sounds good to me :) 👍

**Comment by slouken** [comment]
I updated the verbiage a bit and checked in, thanks for the feedback!
