### ISSUE TITLE
TTF_GetTextSubString can crash confusingly...

### ISSUE THREAD

**Issue by ThrudTheBarbarian** [libsdl-org/SDL_ttf#446]
If (*cough*) you happen to call TTF_CreateText(...) with a NULL font, the TTF_Text object is happily returned without any reported issues, and then if you happen to (*cough*) call TTF_GetTextSubString(..) the application will crash in 

```
    if (text->internal->num_clusters == 0) {
        substring->rect.h = text->internal->font->height;
        return true;
    }
```

... because 'font' is NULL and you end up dereferencing it. It'd be nice to have a test in TTF_CreateText() which checks for a NULL font being passed in. 

That way, when you cut/paste some code in a seemingly unrelated part of the application, you won't spend half the day trying to  figure out why *this* application works fine, but *that* one (the 'simple' one) crashes with seemingly-valid input values to TTF_GetTextSubString() :)

**Comment by slouken** [comment]
We should fix that location, but it's actually valid to create a text object with a NULL font and then set or change the font later.

**Comment by ThrudTheBarbarian** [comment]
Yep, makes sense. I was thinking it might be easier to "fix it" in one place than in all the other places that use the font pointer (of which I assume there are legion) but I didn't realise it was valid to initialise it with NULL ...

**Comment by slouken** [comment]
Fixed, thanks!
