### ISSUE TITLE
Build error for GL ES only system

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#51]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2014-07-03 21:29:46 +0000, Maarten ter Huurne wrote:

> The current configure script will #include "SDL_opengl.h" and if that defines "GLuint" it concludes that it can link with OpenGL. This conclusion is incorrect for many embedded Linux systems that have GL ES but not the full OpenGL: the GLuint type exists there, but linking with "-lGL" won't work. As a result the build breaks.
> 
> One way to solve this would be to use the proper link flags for GL ES. However, that won't work on systems that only provide the GL ES 2.0 API, since functions like glMatrixMode() are used by glfont.c and are no longer available in GL ES 2.0 and later. So I wouldn't recommend this approach.
> 
> The solution I used is to #include "SDL_config.h" and then check whether it defines SDL_VIDEO_OPENGL:
> 
>  #include "SDL_config.h"
> 
>  #ifndef SDL_VIDEO_OPENGL
>  #error SDL2 built without OpenGL support
>  #endif
> 
> For completeness sake, here is the build log fragment containing the error:
> 
> libtool: link: /home/mth/gcw0/buildroot/output/host/usr/bin/mipsel-gcw0-linux-uclibc-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -pipe -O2 -I/home/mth/gcw0/buildroot/output/host/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/include/freetype2 -I/home/mth/gcw0/buildroot/output/host/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/include/SDL2 -D_REENTRANT -DHAVE_OPENGL -o glfont glfont.o  ./.libs/libSDL2_ttf.so -L/home/mth/gcw0/buildroot/output/host/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/lib -lGL -lm /home/mth/gcw0/buildroot/output/host/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/lib/libfreetype.so -lz -lbz2 /home/mth/gcw0/buildroot/output/host/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/lib/libpng14.so /home/mth/gcw0/buildroot/output/host/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/lib/libSDL2.so -lpthread -Wl,-rpath -Wl,/home/mth/gcw0/buildroot/output/build/sdl2_ttf-2.0.12/.libs -Wl,-rpath -Wl,/home/mth/gcw0/buildroot/output/host/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/lib -Wl,-rpath -Wl,/home/mth/gcw0/buildroot/output/host/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/lib
> /home/mth/gcw0/buildroot/output/host/usr/lib/gcc/mipsel-gcw0-linux-uclibc/4.9.0/../../../../mipsel-gcw0-linux-uclibc/bin/ld: cannot find -lGL
> collect2: error: ld returned 1 exit status
> make[1]: *** [glfont] Error 1
> make[1]: Leaving directory `/home/mth/gcw0/buildroot/output/build/sdl2_ttf-2.0.12'

On 2014-10-15 22:42:35 +0000, Gabriel Jacobo wrote:

> Your proposed fix works, but it solves the problem partially since you have to conditionally disable building glfont (right now it's going to be built no matter what). Sadly my system (Ubuntu 14.04) wants to update a bunch of files to auto* 1.14 thus making it hard for me to create a sane patch which leaves the configure script working also in older systems.

On 2014-10-15 22:49:14 +0000, Gabriel Jacobo wrote:

> Sam or Ryan, is it safe to update those files (aclocal.m4, Makefile.am, Makefile.in) that autogen.sh is updating without me wanting it to ? :)

**Comment by SupervisedThinking** [comment]
Usually I've patched out OpenGL for SBC builds:

https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/multimedia/SDL/sdl2_ttf/patches/no-opengl/sdl2_ttf-100.01-enable-opengl-only-for-X11.patch

But it should only link against it once libGL or something similar is present, don't check only for headers like GL/gl.h because atm mesa will always install them even for OpenGLES only builds

**Comment by sezero** [comment]
This should already be fixed by https://github.com/libsdl-org/SDL_ttf/commit/200901a8f55bcf
which explicitly checks OpenGL linkage.
