### ISSUE TITLE
Unable to load font from cyrilic folder path

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#64]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2015-10-09 22:43:08 +0000, Dimitry wrote:

> When trying to load font from a path  /user/Папка/font.ttf
> it would result in an error and the pointer returned as 0.

On 2015-10-10 20:03:02 +0000, Philipp Wiesemann wrote:

> Thank you for reporting this problem.
> 
> What is the error message returned by TTF_GetError() after loading the font failed?

**Comment by slouken** [comment]
This should be fixed with the latest version of SDL. Please reopen this bug if it's still active.
