### ISSUE TITLE
configure --enable-shared=no does not work

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#69]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Other, x86

# Comments on the original bug report:

On 2016-08-26 21:18:27 +0000, Intellectual Kitty wrote:

> Using the --enable-shared=no with configure still tries to build with shared libraries.  (Note that the --enable-shared=no option DOES work with SDL, SDL_image, and SDL_net, which are all the other projects that I have built.)
> 
> The following is output from running make after running configure with --enable-shared=no.  Note that I have the static version of the libpng16 library installed under /usr/local/lib/ but not the shared version.
> 
> /bin/sh ./libtool  --tag=CC   --mode=link gcc  -g -O2 -I/usr/local/include/freetype2 -I/usr/local/include/SDL2 -D_THREAD_SAFE -DHAVE_OPENGL   -o showfont showfont.o libSDL2_ttf.la -L/usr/local/lib -lfreetype -L/usr/local/lib -lSDL2 -lm -liconv -Wl,-framework,ForceFeedback -lobjc -Wl,-framework,CoreVideo -Wl,-framework,Cocoa -Wl,-framework,Carbon -Wl,-framework,IOKit -Wl,-framework,CoreAudio -Wl,-framework,AudioToolbox -Wl,-framework,AudioUnit
> libtool: link: gcc -g -O2 -I/usr/local/include/freetype2 -I/usr/local/include/SDL2 -D_THREAD_SAFE -DHAVE_OPENGL -o showfont showfont.o -Wl,-framework -Wl,ForceFeedback -Wl,-framework -Wl,CoreVideo -Wl,-framework -Wl,Cocoa -Wl,-framework -Wl,Carbon -Wl,-framework -Wl,IOKit -Wl,-framework -Wl,CoreAudio -Wl,-framework -Wl,AudioToolbox -Wl,-framework -Wl,AudioUnit  ./.libs/libSDL2_ttf.a -L/usr/local/lib /usr/local/lib/libfreetype.a -lbz2 /usr/local/lib/libpng16.dylib -lz /usr/local/lib/libSDL2.a -lm -liconv -lobjc
> clang: error: no such file or directory: '/usr/local/lib/libpng16.dylib'

On 2020-03-13 21:30:42 +0000, Hugh McLenaghan wrote:

> I'm having a similar issue to this one now.  Using SDL_ttf version 2.0.15.
> 
> My application is set to use Static Libraries, everything compiles fine.   When I try to run it I get an exception.  If I copy the SDL2_ttf.dll to the runtime directory, then the program works.  This means that somehow it's still needing the dynamic library even although it's supposed to be compiled as static.

On 2020-03-13 21:31:33 +0000, Hugh McLenaghan wrote:

> PS, i'm building a Windows .exe file and using Visual Studio 2019, with the /MT option.

**Comment by slouken** [comment]
I believe this is fixed, with SDL_ttf 2.0.18 including FreeType and Harfbuzz directly.
